package dev.franzueto.fluxit.tokens

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldContainExactlyInAnyOrder
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import java.io.File

class KotlinEmitterTest : FunSpec({

    test("emits five expected files with the correct package") {
        val doc = TokenParser.parse(sampleTokensJson())
        val files = KotlinEmitter.emit(doc)

        files.keys shouldContainExactlyInAnyOrder listOf(
            "FluxItColors.kt",
            "FluxItSpacing.kt",
            "FluxItShapes.kt",
            "FluxItTypography.kt",
            "FluxItElevation.kt",
        )
        files.values.forEach { it shouldContain "package dev.franzueto.fluxit.core.designsystem.tokens" }
    }

    test("color literals use Compose AARRGGBB hex form") {
        val doc = TokenParser.parse(sampleTokensJson())
        val colors = KotlinEmitter.emit(doc).getValue("FluxItColors.kt")

        // primary.blue = #2b7cee (fully opaque) → 0xFF2B7CEE.
        colors shouldContain "primaryBlue: Color = Color(0xFF2B7CEE)"
        // primary.blueShadow = #2b7cee @ 40% (0x66) → 0x662B7CEE.
        colors shouldContain "primaryBlueShadow: Color = Color(0x662B7CEE)"
        // surface.cardMuted = #1e263280 → 0x801E2632.
        colors shouldContain "surfaceCardMuted: Color = Color(0x801E2632)"
    }

    test("spacing emits Dp literals, shapes emit RoundedCornerShape") {
        val doc = TokenParser.parse(sampleTokensJson())
        val files = KotlinEmitter.emit(doc)

        files.getValue("FluxItSpacing.kt") shouldContain "containerPadding: Dp = 16.dp"
        files.getValue("FluxItSpacing.kt") shouldContain "scaleXs: Dp = 4.dp"
        files.getValue("FluxItShapes.kt") shouldContain "md: Shape = RoundedCornerShape(12.dp)"
        files.getValue("FluxItShapes.kt") shouldContain "full: Shape = RoundedCornerShape(9999.dp)"
    }

    test("typography emits TextStyle with em-based lineHeight + letterSpacing") {
        val doc = TokenParser.parse(sampleTokensJson())
        val typo = KotlinEmitter.emit(doc).getValue("FluxItTypography.kt")

        typo shouldContain "displayLg: TextStyle = TextStyle("
        typo shouldContain "fontSize = 32.sp"
        typo shouldContain "fontWeight = FontWeight(700)"
        typo shouldContain "lineHeight = 1.2.em"
        typo shouldContain "letterSpacing = -0.02.em"
        // Phase 02 §3: Inter is now bundled; the emitter references the
        // FontFamily.Companion.Inter extension declared in androidMain
        // (see core-designsystem/.../typography/FluxItFonts.kt).
        typo shouldContain "fontFamily = FontFamily.Inter"
        typo shouldContain "import dev.franzueto.fluxit.core.designsystem.typography.Inter"
    }

    test("elevation emits a data class and zero-shadow level0/level1") {
        val doc = TokenParser.parse(sampleTokensJson())
        val elev = KotlinEmitter.emit(doc).getValue("FluxItElevation.kt")

        elev shouldContain "data class FluxItElevationValue"
        elev shouldContain "level0: FluxItElevationValue = FluxItElevationValue("
        elev shouldContain "color = Color(0x00000000)"
        elev shouldContain "blur = 0.dp"
    }

    test("descriptions become KDoc comments on the property") {
        val doc = TokenParser.parse(sampleTokensJson())
        val colors = KotlinEmitter.emit(doc).getValue("FluxItColors.kt")

        // primary.blue has $description = "Primary CTA, FAB, active-tab tint."
        colors shouldContain "/** Primary CTA, FAB, active-tab tint. */"
    }

    test("the real tokens.json checked into the repo emits clean output") {
        // build-logic test cwd = build-logic/, so the repo root is one up.
        val realTokens = File("../core/core-designsystem/tokens/tokens.json")
        check(realTokens.exists()) { "Fixture missing: ${realTokens.absolutePath}" }

        val doc = TokenParser.parse(realTokens)
        val files = KotlinEmitter.emit(doc)

        // Sanity: every file has the generated-header banner and a package decl.
        files.values.forEach {
            it shouldContain "AUTO-GENERATED by :core:core-designsystem:generateTokens"
            it shouldContain "package dev.franzueto.fluxit.core.designsystem.tokens"
            // No alias placeholders should leak through.
            it shouldNotContain "{font.family"
        }
    }
})

private fun sampleTokensJson(): String = """
    {
      "font": {
        "family": {
          "inter": { "${'$'}type": "fontFamily", "${'$'}value": ["Inter", "system-ui"] }
        }
      },
      "shape": {
        "${'$'}type": "dimension",
        "md":   { "${'$'}value": "12px" },
        "full": { "${'$'}value": "9999px" }
      },
      "spacing": {
        "${'$'}type": "dimension",
        "containerPadding": { "${'$'}value": "16px" },
        "scale": { "xs": { "${'$'}value": "4px" } }
      },
      "dark": {
        "color": {
          "${'$'}type": "color",
          "surface":  { "cardMuted": { "${'$'}value": "#1e263280" } },
          "primary":  {
            "blue":       { "${'$'}value": "#2b7cee", "${'$'}description": "Primary CTA, FAB, active-tab tint." },
            "blueShadow": { "${'$'}value": "#2b7cee66" }
          }
        },
        "typography": {
          "${'$'}type": "typography",
          "displayLg": {
            "${'$'}value": {
              "fontFamily": "{font.family.inter}",
              "fontWeight": 700,
              "fontSize": "32px",
              "lineHeight": 1.2,
              "letterSpacing": "-0.02em"
            }
          }
        },
        "elevation": {
          "${'$'}type": "shadow",
          "level0": {
            "${'$'}value": { "color": "#00000000", "offsetX": "0px", "offsetY": "0px", "blur": "0px", "spread": "0px" }
          }
        }
      }
    }
""".trimIndent()
