package dev.franzueto.fluxit.tokens

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldContainExactly
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import java.io.File

class SwiftEmitterTest : FunSpec({

    test("emits a single FluxItTokens.swift file") {
        val doc = TokenParser.parse(sampleSwiftTokensJson())
        val files = SwiftEmitter.emit(doc)
        files.keys.toList() shouldContainExactly listOf("FluxItTokens.swift")
        files.values.single() shouldContain "import SwiftUI"
        files.values.single() shouldContain "public enum FluxItTokens {"
    }

    test("colors emit SwiftUI.Color initializers normalized to 0...1 components") {
        val doc = TokenParser.parse(sampleSwiftTokensJson())
        val src = SwiftEmitter.emit(doc).getValue("FluxItTokens.swift")

        // #2b7cee at full opacity → r=43/255, g=124/255, b=238/255, a=1.
        src shouldContain "primaryBlue: Color = Color(.sRGB, red: 0.168627, green: 0.486275, blue: 0.933333, opacity: 1.0)"
        // 40% alpha = 0x66 = 102 → 102/255 ≈ 0.4.
        src shouldContain "primaryBlueShadow:"
        src shouldContain "opacity: 0.4"
    }

    test("spacing emits CGFloat with integer literals where exact") {
        val src = SwiftEmitter.emit(TokenParser.parse(sampleSwiftTokensJson()))
            .getValue("FluxItTokens.swift")

        src shouldContain "containerPadding: CGFloat = 16"
        src shouldContain "scaleXs: CGFloat = 4"
    }

    test("shapes emit CGFloat radii inside FluxItTokens.Shapes") {
        val src = SwiftEmitter.emit(TokenParser.parse(sampleSwiftTokensJson()))
            .getValue("FluxItTokens.swift")

        src shouldContain "public enum Shapes {"
        src shouldContain "md: CGFloat = 12"
        src shouldContain "full: CGFloat = 9999"
    }

    test("typography emits TypographyStyle with em→pt tracking conversion + weight mapping") {
        val src = SwiftEmitter.emit(TokenParser.parse(sampleSwiftTokensJson()))
            .getValue("FluxItTokens.swift")

        src shouldContain "public struct TypographyStyle {"
        // displayLg: fontSize 32, weight 700 (.bold), lineHeight 1.2,
        // tracking = -0.02 × 32 = -0.64.
        src shouldContain "displayLg = TypographyStyle("
        src shouldContain "font: .system(size: 32, weight: .bold)"
        src shouldContain "lineHeight: 1.2"
        src shouldContain "tracking: -0.64"
    }

    test("elevation emits ElevationValue with explicit RGB(A) on every component") {
        val src = SwiftEmitter.emit(TokenParser.parse(sampleSwiftTokensJson()))
            .getValue("FluxItTokens.swift")

        src shouldContain "public struct ElevationValue {"
        src shouldContain "level0 = ElevationValue("
        src shouldContain "color: Color(.sRGB, red: 0.0, green: 0.0, blue: 0.0, opacity: 0.0)"
        src shouldContain "blur: 0"
    }

    test("the real tokens.json checked into the repo emits a syntactically reasonable file") {
        val real = File("../core/core-designsystem/tokens/tokens.json")
        check(real.exists()) { "Fixture missing: ${real.absolutePath}" }

        val src = SwiftEmitter.emit(TokenParser.parse(real)).getValue("FluxItTokens.swift")

        src shouldContain "AUTO-GENERATED by :core:core-designsystem:generateTokens"
        // Surface tokens present.
        src shouldContain "surfaceCard:"
        src shouldContain "surfaceCardMuted:"
        // No alias placeholder leaked through.
        src shouldNotContain "{font.family"
        // Balanced braces — count must match.
        val opens = src.count { it == '{' }
        val closes = src.count { it == '}' }
        check(opens == closes) { "Unbalanced braces in generated Swift: $opens opens vs $closes closes" }
    }
})

private fun sampleSwiftTokensJson(): String = """
    {
      "font": {
        "family": {
          "inter": { "${'$'}type": "fontFamily", "${'$'}value": ["Inter", "system-ui"] }
        }
      },
      "shape": {
        "${'$'}type": "dimension",
        "md":   { "${'$'}value": "12px" },
        "full": { "${'$'}value": "9999px" }
      },
      "spacing": {
        "${'$'}type": "dimension",
        "containerPadding": { "${'$'}value": "16px" },
        "scale": { "xs": { "${'$'}value": "4px" } }
      },
      "dark": {
        "color": {
          "${'$'}type": "color",
          "primary": {
            "blue":       { "${'$'}value": "#2b7cee" },
            "blueShadow": { "${'$'}value": "#2b7cee66" }
          }
        },
        "typography": {
          "${'$'}type": "typography",
          "displayLg": {
            "${'$'}value": {
              "fontFamily": "{font.family.inter}",
              "fontWeight": 700,
              "fontSize": "32px",
              "lineHeight": 1.2,
              "letterSpacing": "-0.02em"
            }
          }
        },
        "elevation": {
          "${'$'}type": "shadow",
          "level0": {
            "${'$'}value": { "color": "#00000000", "offsetX": "0px", "offsetY": "0px", "blur": "0px", "spread": "0px" }
          }
        }
      }
    }
""".trimIndent()
