package dev.franzueto.fluxit.icons

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldNotBeEmpty
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import java.io.File

class KotlinIconEmitterTest : FunSpec({

    test("emits a FluxItIcons.kt file in the designsystem.icons package with the expected header") {
        val emitted = KotlinIconEmitter.emit(listOf(IconSource("cart", 0.0, 0.0, 24.0, 24.0, emptyList())))
        emitted.keys shouldBe setOf("FluxItIcons.kt")

        val text = emitted.getValue("FluxItIcons.kt")
        text shouldContain "AUTO-GENERATED by :core:core-designsystem:generateIcons"
        text shouldContain "package dev.franzueto.fluxit.core.designsystem.icons"
        text shouldContain "import androidx.compose.ui.graphics.vector.ImageVector"
        text shouldContain "public object FluxItIcons"
    }

    test("emits a real Material Symbols glyph (plus) with shifted absolute Y coords") {
        // plus.svg: viewBox="0 -960 960 960", path="M440-440H200v-80h240v-240h80v240h240v80H520v240h-80v-240Z"
        // Expected:
        //   - viewport 960×960
        //   - M440,-440 (abs) → moveTo(440f, 520f) — Y shifted by -(-960) = +960
        //   - H200 (abs)     → horizontalLineTo(200f)
        //   - v-80 (rel)     → verticalLineToRelative(-80f) — relative deltas unshifted
        //   - …
        //   - Z              → close()
        val plus = IconSource(
            name = "plus",
            viewBoxMinX = 0.0,
            viewBoxMinY = -960.0,
            viewBoxWidth = 960.0,
            viewBoxHeight = 960.0,
            commands = listOf(
                MoveTo(440.0, -440.0, relative = false),
                HorizontalLineTo(200.0, relative = false),
                VerticalLineTo(-80.0, relative = true),
                HorizontalLineTo(240.0, relative = true),
                VerticalLineTo(-240.0, relative = true),
                HorizontalLineTo(80.0, relative = true),
                VerticalLineTo(240.0, relative = true),
                HorizontalLineTo(240.0, relative = true),
                VerticalLineTo(80.0, relative = true),
                HorizontalLineTo(520.0, relative = false),
                VerticalLineTo(240.0, relative = true),
                HorizontalLineTo(-80.0, relative = true),
                VerticalLineTo(-240.0, relative = true),
                Close,
            ),
        )

        val text = KotlinIconEmitter.emit(listOf(plus)).getValue("FluxItIcons.kt")

        text shouldContain "public val FluxItIcons.Plus: ImageVector"
        text shouldContain "name = \"FluxItIcons.Plus\","
        text shouldContain "viewportWidth = 960f,"
        text shouldContain "viewportHeight = 960f,"
        // Absolute M440 -440 → Y shifted +960
        text shouldContain "moveTo(440f, 520f)"
        // Absolute H200 → no shift on X (Material Symbols has viewBoxMinX=0)
        text shouldContain "horizontalLineTo(200f)"
        // Relative v-80 stays as -80 (delta is translation-invariant)
        text shouldContain "verticalLineToRelative(-80f)"
        // Absolute H520 with no shift
        text shouldContain "horizontalLineTo(520f)"
        text shouldContain "close()"
        // Memoization backing field at file scope
        text shouldContain "private var _plus: ImageVector? = null"
        // Don't accidentally emit raw SVG hex fill
        text shouldNotContain "#1f1f1f"
    }

    test("translates every PathCommand variant correctly (smoke shape)") {
        val all = IconSource(
            name = "all-cmds",
            viewBoxMinX = 0.0, viewBoxMinY = 0.0,
            viewBoxWidth = 24.0, viewBoxHeight = 24.0,
            commands = listOf(
                MoveTo(0.0, 0.0, false),
                MoveTo(1.0, 1.0, true),
                LineTo(2.0, 2.0, false),
                LineTo(3.0, 3.0, true),
                HorizontalLineTo(4.0, false),
                HorizontalLineTo(5.0, true),
                VerticalLineTo(6.0, false),
                VerticalLineTo(7.0, true),
                CurveTo(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, false),
                CurveTo(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, true),
                ReflectiveCurveTo(1.0, 2.0, 3.0, 4.0, false),
                ReflectiveCurveTo(1.0, 2.0, 3.0, 4.0, true),
                QuadTo(1.0, 2.0, 3.0, 4.0, false),
                QuadTo(1.0, 2.0, 3.0, 4.0, true),
                ReflectiveQuadTo(1.0, 2.0, false),
                ReflectiveQuadTo(3.0, 4.0, true),
                Close,
            ),
        )

        val text = KotlinIconEmitter.emit(listOf(all)).getValue("FluxItIcons.kt")
        listOf(
            "moveTo(0f, 0f)",
            "moveToRelative(1f, 1f)",
            "lineTo(2f, 2f)",
            "lineToRelative(3f, 3f)",
            "horizontalLineTo(4f)",
            "horizontalLineToRelative(5f)",
            "verticalLineTo(6f)",
            "verticalLineToRelative(7f)",
            "curveTo(1f, 2f, 3f, 4f, 5f, 6f)",
            "curveToRelative(1f, 2f, 3f, 4f, 5f, 6f)",
            "reflectiveCurveTo(1f, 2f, 3f, 4f)",
            "reflectiveCurveToRelative(1f, 2f, 3f, 4f)",
            "quadTo(1f, 2f, 3f, 4f)",
            "quadToRelative(1f, 2f, 3f, 4f)",
            "reflectiveQuadTo(1f, 2f)",
            "reflectiveQuadToRelative(3f, 4f)",
            "close()",
        ).forEach { call -> text shouldContain call }
    }

    test("kebab-case filenames convert to PascalCase identifiers and lowerCamel backing fields") {
        val icons = listOf("cart", "chevron-right", "list-filled", "account-filled")
            .map { IconSource(it, 0.0, 0.0, 24.0, 24.0, emptyList()) }
        val text = KotlinIconEmitter.emit(icons).getValue("FluxItIcons.kt")

        listOf(
            "FluxItIcons.Cart",
            "FluxItIcons.ChevronRight",
            "FluxItIcons.ListFilled",
            "FluxItIcons.AccountFilled",
            "private var _cart:",
            "private var _chevronRight:",
            "private var _listFilled:",
            "private var _accountFilled:",
        ).forEach { token -> text shouldContain token }
    }

    test("emits a stable, alphabetically-sorted property order") {
        val icons = listOf("zebra", "alpha", "mango")
            .map { IconSource(it, 0.0, 0.0, 24.0, 24.0, emptyList()) }
        val text = KotlinIconEmitter.emit(icons).getValue("FluxItIcons.kt")

        val alphaPos = text.indexOf("FluxItIcons.Alpha:")
        val mangoPos = text.indexOf("FluxItIcons.Mango:")
        val zebraPos = text.indexOf("FluxItIcons.Zebra:")
        check(alphaPos in 1 until mangoPos && mangoPos < zebraPos) {
            "Icons should be alphabetically ordered; got positions $alphaPos / $mangoPos / $zebraPos"
        }
    }

    test("emits every real SVG in core/core-designsystem/icons/ without throwing") {
        // Mirrors the parser smoke test. Catches emitter regressions (e.g.
        // an unhandled PathCommand subtype) when icons are added.
        val iconsDir = File("../core/core-designsystem/icons")
        val parsed = iconsDir.listFiles { f -> f.extension == "svg" }
            ?.map { SvgPathParser.parse(it) }
            .orEmpty()
        parsed.shouldNotBeEmpty()

        val text = KotlinIconEmitter.emit(parsed).getValue("FluxItIcons.kt")
        parsed.forEach { icon ->
            // Each icon should appear exactly once as a property declaration.
            val id = icon.name.split('-').joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }
            text shouldContain "FluxItIcons.$id:"
        }
    }
})
