package dev.franzueto.fluxit.icons

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldHaveSize
import io.kotest.matchers.collections.shouldNotBeEmpty
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldContain
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.boolean
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File

class SwiftIconEmitterTest : FunSpec({

    val json = Json { ignoreUnknownKeys = true }

    test("root xcassets Contents.json is the standard Xcode namespace metadata") {
        val out = SwiftIconEmitter.emit(listOf(stubIcon("cart")))
        val obj = json.parseToJsonElement(out.xcassetsRootContentsJson).jsonObject
        val info = obj["info"]!!.jsonObject
        info["author"]!!.jsonPrimitive.content shouldBe "xcode"
        info["version"]!!.jsonPrimitive.int shouldBe 1
    }

    test("imageset Contents.json marks the SVG as template-rendering + vector-preserving") {
        val out = SwiftIconEmitter.emit(listOf(stubIcon("cart")))
        val entry = out.imagesets.single { it.imagesetName == "ic-cart" }
        val obj = json.parseToJsonElement(entry.contentsJson).jsonObject

        val images = obj["images"]!!.jsonArray
        images shouldHaveSize 1
        val img = images.single().jsonObject
        img["filename"]!!.jsonPrimitive.content shouldBe "ic-cart.svg"
        img["idiom"]!!.jsonPrimitive.content shouldBe "universal"

        val props = obj["properties"]!!.jsonObject
        props["template-rendering-intent"]!!.jsonPrimitive.content shouldBe "template"
        props["preserves-vector-representation"]!!.jsonPrimitive.boolean shouldBe true
    }

    test("ImageSetEntry routes source SVG filename to ic-prefixed output filename") {
        val out = SwiftIconEmitter.emit(listOf(stubIcon("chevron-right")))
        val entry = out.imagesets.single()
        entry.imagesetName shouldBe "ic-chevron-right"
        entry.sourceSvgFilename shouldBe "chevron-right.svg"
        entry.outputSvgFilename shouldBe "ic-chevron-right.svg"
    }

    test("Swift accessor file extends FluxItTokens with an Icons enum") {
        val icons = listOf("cart", "chevron-right", "list-filled", "account-filled").map(::stubIcon)
        val src = SwiftIconEmitter.emit(icons).swiftAccessorSource

        src shouldContain "// AUTO-GENERATED by :core:core-designsystem:generateIcons"
        src shouldContain "import SwiftUI"
        src shouldContain "public extension FluxItTokens {"
        src shouldContain "    enum Icons {"
        // kebab → lowerCamelCase identifiers, "ic-" prefix on the Image name string
        src shouldContain "public static let cart: Image = Image(\"ic-cart\")"
        src shouldContain "public static let chevronRight: Image = Image(\"ic-chevron-right\")"
        src shouldContain "public static let listFilled: Image = Image(\"ic-list-filled\")"
        src shouldContain "public static let accountFilled: Image = Image(\"ic-account-filled\")"
    }

    test("imagesets are sorted alphabetically by source-file stem") {
        val icons = listOf("zebra", "alpha", "mango").map(::stubIcon)
        val out = SwiftIconEmitter.emit(icons)
        out.imagesets.map { it.imagesetName } shouldBe listOf("ic-alpha", "ic-mango", "ic-zebra")
    }

    test("Swift accessor entries are sorted alphabetically by identifier") {
        val icons = listOf("zebra", "alpha", "mango").map(::stubIcon)
        val src = SwiftIconEmitter.emit(icons).swiftAccessorSource
        val alphaPos = src.indexOf("static let alpha:")
        val mangoPos = src.indexOf("static let mango:")
        val zebraPos = src.indexOf("static let zebra:")
        check(alphaPos in 1 until mangoPos && mangoPos < zebraPos) {
            "Accessors should be alphabetically ordered; got positions $alphaPos / $mangoPos / $zebraPos"
        }
    }

    test("emits every real SVG in core/core-designsystem/icons/ without throwing") {
        // Mirrors the parser + Kotlin-emitter smoke tests.
        val iconsDir = File("../core/core-designsystem/icons")
        val parsed = iconsDir.listFiles { f -> f.extension == "svg" }
            ?.map { SvgPathParser.parse(it) }
            .orEmpty()
        parsed.shouldNotBeEmpty()

        val out = SwiftIconEmitter.emit(parsed)
        out.imagesets shouldHaveSize parsed.size

        // Each imageset's Contents.json should parse as JSON (catches escaping
        // bugs from unusual icon names).
        out.imagesets.forEach { entry ->
            json.parseToJsonElement(entry.contentsJson).jsonObject shouldNotBe null
            entry.imagesetName shouldContain "ic-"
        }

        // Every icon should appear in the Swift accessor file.
        parsed.forEach { icon ->
            val expectedId = icon.name.split('-').let { parts ->
                parts.first() + parts.drop(1).joinToString("") {
                    it.replaceFirstChar(Char::uppercaseChar)
                }
            }
            out.swiftAccessorSource shouldContain "static let $expectedId:"
            out.swiftAccessorSource shouldContain "Image(\"ic-${icon.name}\")"
        }
    }
})

private fun stubIcon(name: String): IconSource =
    IconSource(name = name, viewBoxMinX = 0.0, viewBoxMinY = 0.0, viewBoxWidth = 24.0, viewBoxHeight = 24.0, commands = emptyList())
