import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.googleServices)
}

// Single source of truth for the Firebase emulator endpoints, generated
// into commonMain so the Android adapter and the iOS adapter
// read exactly the same host/ports. Values come from `gradle.properties` and are
// overridable per developer (see the comment block there) so the collision-prone
// Firestore default port 8080 never has to be hard-coded into client code.
// The generated object holds plain constants only - no Firebase SDK types.
//
// FirebaseDevFlags retains constant compatibility metadata after. Repository
// selection is unconditional in each actual platformModule(), independent of properties.
abstract class GenerateFirebaseEmulatorConfig : DefaultTask() {
    @get:Input
    abstract val emulatorEnabled: Property<Boolean>

    @get:Input
    abstract val host: Property<String>

    @get:Input
    abstract val authPort: Property<Int>

    @get:Input
    abstract val firestorePort: Property<Int>

    @get:Input
    abstract val storagePort: Property<Int>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val outputRoot = outputDirectory.get().asFile
        // Remove the predecessor package from so stale generated sources
        // cannot keep a commonMain-visible `firebase` namespace alive.
        outputRoot.resolve("com/fluxit/firebase").deleteRecursively()
        val packageDir = outputRoot.resolve("com/fluxit/config")
        packageDir.mkdirs()
        packageDir.resolve("FirebaseEmulatorConfig.kt").writeText(
            """
            |// Generated by the :composeApp:generateFirebaseEmulatorConfig Gradle task.
            |// Do not edit. Change the `fluxit.firebase.*` Gradle properties instead.
            |package com.fluxit.config
            |
            |/**
            | * Build-time Firebase emulator endpoint configuration shared by every target.
            | *
            | * Contains plain constants only; platform adapters in `androidMain`/`iosMain`
            | * translate these into the respective Firebase SDK's `useEmulator` calls.
            | */
            |public object FirebaseEmulatorConfig {
            |    public const val ENABLED: Boolean = ${emulatorEnabled.get()}
            |    public const val HOST: String = "${host.get()}"
            |    public const val AUTH_PORT: Int = ${authPort.get()}
            |    public const val FIRESTORE_PORT: Int = ${firestorePort.get()}
            |    public const val STORAGE_PORT: Int = ${storagePort.get()}
            |}
            |
            |/**
            | * Compatibility metadata. Production Koin modules unconditionally bind
            | * Firebase; the retired fluxit.firebase.repositories.enabled property is ignored.
            | */
            |public object FirebaseDevFlags {
            |    public const val USE_FIREBASE_REPOSITORIES: Boolean = true
            |}
            |
            """.trimMargin()
        )
    }
}

val generateFirebaseEmulatorConfig =
    tasks.register<GenerateFirebaseEmulatorConfig>("generateFirebaseEmulatorConfig") {
        description = "Generates the shared Firebase emulator endpoint and dev-flag constants."
        emulatorEnabled.set(
            providers.gradleProperty("fluxit.firebase.emulator.enabled")
                .map { it.toBoolean() }
                .orElse(false)
        )
        host.set(providers.gradleProperty("fluxit.firebase.emulator.host").orElse("127.0.0.1"))
        authPort.set(
            providers.gradleProperty("fluxit.firebase.emulator.auth.port").map { it.toInt() }.orElse(9099)
        )
        firestorePort.set(
            providers.gradleProperty("fluxit.firebase.emulator.firestore.port").map { it.toInt() }.orElse(8080)
        )
        storagePort.set(
            providers.gradleProperty("fluxit.firebase.emulator.storage.port").map { it.toInt() }.orElse(9199)
        )
        outputDirectory.set(layout.buildDirectory.dir("generated/fluxit/firebaseEmulatorConfig/kotlin"))
    }

// Web Firebase app config (Console → Project settings → Your apps → Web app), saved by
// each developer as the gitignored `composeApp/firebase-web-config.json` (template:
// `firebase-web-config.example.json`). Generated into wasmJsMain only. A missing file
// generates `options = null` so the web target still compiles and tests; the production
// bundle refuses to build without it. Error messages name keys, never values.
abstract class GenerateFirebaseWebConfig : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val configFile: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val source = configFile.files.singleOrNull()?.takeIf { it.isFile }
        val options = source?.let { file ->
            // The parser's own message quotes the offending line, so it is replaced, and the
            // cause is not chained (Gradle prints causes too).
            val parsed = try {
                groovy.json.JsonSlurper().parse(file)
            } catch (_: Exception) {
                throw GradleException(
                    "${file.name}: not valid JSON (keys and strings need double quotes; paste only the values, " +
                        "not the console's `const firebaseConfig = {...}` snippet)"
                )
            }
            @Suppress("UNCHECKED_CAST")
            val json = parsed as? Map<String, Any?>
                ?: throw GradleException("${file.name}: expected a JSON object")
            REQUIRED_KEYS.associateWith { key ->
                val value = json[key] as? String
                if (value.isNullOrBlank()) throw GradleException("${file.name}: missing or blank '$key'")
                if (!SAFE_VALUE.matches(value)) throw GradleException("${file.name}: unexpected characters in '$key'")
                if ("REPLACE_WITH" in value) throw GradleException("${file.name}: '$key' still has its template placeholder")
                value
            }
        }
        val outputRoot = outputDirectory.get().asFile
        val packageDir = outputRoot.resolve("com/fluxit/config")
        packageDir.mkdirs()
        val body = options?.let {
            "FirebaseWebOptions(\n" +
                REQUIRED_KEYS.joinToString("") { key -> "        $key = \"${it.getValue(key)}\",\n" } +
                "    )"
        } ?: "null"
        packageDir.resolve("FirebaseWebConfig.kt").writeText(
            """
            |// Generated by the :composeApp:generateFirebaseWebConfig Gradle task.
            |// Do not edit. Change composeApp/firebase-web-config.json instead.
            |package com.fluxit.config
            |
            |internal object FirebaseWebConfig {
            |    /** Null when composeApp/firebase-web-config.json was absent at build time. */
            |    val options: FirebaseWebOptions? = $body
            |}
            |
            """.trimMargin()
        )
    }

    private companion object {
        val REQUIRED_KEYS = listOf("apiKey", "authDomain", "projectId", "storageBucket", "messagingSenderId", "appId")
        val SAFE_VALUE = Regex("^[A-Za-z0-9._:-]+$")
    }
}

val firebaseWebConfigFile = layout.projectDirectory.file("firebase-web-config.json")

val generateFirebaseWebConfig =
    tasks.register<GenerateFirebaseWebConfig>("generateFirebaseWebConfig") {
        description = "Generates the web Firebase app options from the gitignored firebase-web-config.json."
        configFile.from(firebaseWebConfigFile)
        outputDirectory.set(layout.buildDirectory.dir("generated/fluxit/firebaseWebConfig/kotlin"))
    }

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    // Mobile-first web client (see docs/web-app/PROGRESS.md). Target scope: sign in to an
    // existing account only; sign-up and sample-data seeding are hidden from Phase 1 on.
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("composeApp")
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries.executable()
    }

    // skikoMain/skikoTest: code shared by the targets that render through Skia (iOS and web),
    // such as image decode/resize.
    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    applyDefaultHierarchyTemplate {
        common {
            group("skiko") {
                group("ios")
                withWasmJs()
            }
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateFirebaseEmulatorConfig)
        }
        wasmJsMain {
            kotlin.srcDir(generateFirebaseWebConfig)
        }
        // Firebase regression fixtures are opt-in test code, absent from ordinary app binaries.
        androidInstrumentedTest { kotlin.srcDir("src/firebaseParity/kotlin") }
        if (providers.gradleProperty("fluxit.parity.enabled").orNull == "true") {
            androidInstrumentedTest { kotlin.srcDir("src/firebaseParityAndroid/kotlin") }
            iosMain {
                kotlin.srcDir("src/firebaseParity/kotlin")
                kotlin.srcDir("src/firebaseParityIos/kotlin")
            }
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(libs.material.icons.extended)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.androidx.lifecycle.viewmodel.navigation3)
            implementation(libs.navigation3.ui)
            implementation(libs.koin.core)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kotlinx.serialization.core)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.koin.android)
            implementation(project.dependencies.platform(libs.firebase.bom))
            implementation(libs.firebase.auth)
            implementation(libs.firebase.firestore)
            implementation(libs.firebase.storage)
        }
        wasmJsMain.dependencies {
            // Firebase JS modular SDK, reached only from wasmJsMain/resources/firebase-bridge.mjs.
            implementation(npm("firebase", "12.19.0"))
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
        iosTest.dependencies {
            @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
            implementation(compose.uiTest)
        }
        // Instrumented integration checks for the Android Firebase Auth
        // adapter. They run against the local Auth emulator (see the KDoc on
        // FirebaseAuthEmulatorIntegrationTest), never against a live project.
        androidInstrumentedTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.androidx.test.ext.junit)
            implementation(libs.androidx.test.runner)
            implementation("androidx.compose.ui:ui-test-junit4-android:1.10.4")
            implementation("androidx.test.espresso:espresso-core:3.7.0")
        }
    }
}

android {
    namespace = "com.fluxit"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.fluxit"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

// The deployable web bundle must carry a real Firebase web config and must never point at
// the local emulators (the emulator runs under the dev project ID).
tasks.named("wasmJsBrowserProductionWebpack") {
    val configFile = firebaseWebConfigFile.asFile
    // Same parse as generateFirebaseEmulatorConfig, so no spelling of "true" slips past.
    val emulatorEnabled = providers.gradleProperty("fluxit.firebase.emulator.enabled").orNull.toBoolean()
    doFirst {
        if (emulatorEnabled) {
            throw GradleException(
                "The production web bundle cannot be built with fluxit.firebase.emulator.enabled=true; " +
                    "use the development distribution for emulator runs."
            )
        }
        if (!configFile.isFile) {
            throw GradleException(
                "Missing composeApp/firebase-web-config.json; copy firebase-web-config.example.json and fill it in " +
                    "from Firebase Console → Project settings → Your apps → Web app."
            )
        }
    }
}
