import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.googleServices)
}

// Single source of truth for the Firebase emulator endpoints, generated
// into commonMain so the Android adapter and the iOS adapter
// read exactly the same host/ports. Values come from `gradle.properties` and are
// overridable per developer (see the comment block there) so the collision-prone
// Firestore default port 8080 never has to be hard-coded into client code.
// The generated object holds plain constants only - no Firebase SDK types.
//
// FirebaseDevFlags retains constant compatibility metadata after. Repository
// selection is unconditional in each actual platformModule(), independent of properties.
abstract class GenerateFirebaseEmulatorConfig : DefaultTask() {
    @get:Input
    abstract val emulatorEnabled: Property<Boolean>

    @get:Input
    abstract val host: Property<String>

    @get:Input
    abstract val authPort: Property<Int>

    @get:Input
    abstract val firestorePort: Property<Int>

    @get:Input
    abstract val storagePort: Property<Int>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val outputRoot = outputDirectory.get().asFile
        // Remove the predecessor package from so stale generated sources
        // cannot keep a commonMain-visible `firebase` namespace alive.
        outputRoot.resolve("com/fluxit/firebase").deleteRecursively()
        val packageDir = outputRoot.resolve("com/fluxit/config")
        packageDir.mkdirs()
        packageDir.resolve("FirebaseEmulatorConfig.kt").writeText(
            """
            |// Generated by the :composeApp:generateFirebaseEmulatorConfig Gradle task.
            |// Do not edit. Change the `fluxit.firebase.*` Gradle properties instead.
            |package com.fluxit.config
            |
            |/**
            | * Build-time Firebase emulator endpoint configuration shared by every target.
            | *
            | * Contains plain constants only; platform adapters in `androidMain`/`iosMain`
            | * translate these into the respective Firebase SDK's `useEmulator` calls.
            | */
            |public object FirebaseEmulatorConfig {
            |    public const val ENABLED: Boolean = ${emulatorEnabled.get()}
            |    public const val HOST: String = "${host.get()}"
            |    public const val AUTH_PORT: Int = ${authPort.get()}
            |    public const val FIRESTORE_PORT: Int = ${firestorePort.get()}
            |    public const val STORAGE_PORT: Int = ${storagePort.get()}
            |}
            |
            |/**
            | * Compatibility metadata. Production Koin modules unconditionally bind
            | * Firebase; the retired fluxit.firebase.repositories.enabled property is ignored.
            | */
            |public object FirebaseDevFlags {
            |    public const val USE_FIREBASE_REPOSITORIES: Boolean = true
            |}
            |
            """.trimMargin()
        )
    }
}

val generateFirebaseEmulatorConfig =
    tasks.register<GenerateFirebaseEmulatorConfig>("generateFirebaseEmulatorConfig") {
        description = "Generates the shared Firebase emulator endpoint and dev-flag constants."
        emulatorEnabled.set(
            providers.gradleProperty("fluxit.firebase.emulator.enabled")
                .map { it.toBoolean() }
                .orElse(false)
        )
        host.set(providers.gradleProperty("fluxit.firebase.emulator.host").orElse("127.0.0.1"))
        authPort.set(
            providers.gradleProperty("fluxit.firebase.emulator.auth.port").map { it.toInt() }.orElse(9099)
        )
        firestorePort.set(
            providers.gradleProperty("fluxit.firebase.emulator.firestore.port").map { it.toInt() }.orElse(8080)
        )
        storagePort.set(
            providers.gradleProperty("fluxit.firebase.emulator.storage.port").map { it.toInt() }.orElse(9199)
        )
        outputDirectory.set(layout.buildDirectory.dir("generated/fluxit/firebaseEmulatorConfig/kotlin"))
    }

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateFirebaseEmulatorConfig)
        }
        // Firebase regression fixtures are opt-in test code, absent from ordinary app binaries.
        androidInstrumentedTest { kotlin.srcDir("src/firebaseParity/kotlin") }
        if (providers.gradleProperty("fluxit.parity.enabled").orNull == "true") {
            androidInstrumentedTest { kotlin.srcDir("src/firebaseParityAndroid/kotlin") }
            iosMain {
                kotlin.srcDir("src/firebaseParity/kotlin")
                kotlin.srcDir("src/firebaseParityIos/kotlin")
            }
        }
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(libs.material.icons.extended)
            implementation(libs.androidx.lifecycle.viewmodel.compose)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.androidx.lifecycle.viewmodel.navigation3)
            implementation(libs.navigation3.ui)
            implementation(libs.koin.core)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kotlinx.serialization.core)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.koin.android)
            implementation(project.dependencies.platform(libs.firebase.bom))
            implementation(libs.firebase.auth)
            implementation(libs.firebase.firestore)
            implementation(libs.firebase.storage)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
        iosTest.dependencies {
            @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
            implementation(compose.uiTest)
        }
        // Instrumented integration checks for the Android Firebase Auth
        // adapter. They run against the local Auth emulator (see the KDoc on
        // FirebaseAuthEmulatorIntegrationTest), never against a live project.
        androidInstrumentedTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.androidx.test.ext.junit)
            implementation(libs.androidx.test.runner)
            implementation("androidx.compose.ui:ui-test-junit4-android:1.10.4")
            implementation("androidx.test.espresso:espresso-core:3.7.0")
        }
    }
}

android {
    namespace = "com.fluxit"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.fluxit"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
