package dev.franzueto.fluxit.icons

// Compose / Kotlin emitter for the icon pipeline (ADR-005a).
//
// Returns generated-file basename → full source text. The Gradle task in
// fluxit.designsystem.tokens.gradle.kts (extended in a follow-up commit)
// writes the result to
// core-designsystem/build/generated/source/icons/androidMain/ and registers
// that directory on the androidMain Kotlin source set.
//
// The output uses ImageVector.Builder directly (not the materialIcon helper)
// because Material Symbols ship on a 0..960 viewport — materialIcon hardcodes
// the viewport to 24×24, so we'd lose the coordinate space.
//
// Coordinate-space note: Material Symbols' viewBox is `0 -960 960 960`
// (negative Y origin). Compose's ImageVector viewport implicitly anchors at
// (0, 0), so the emitter shifts every absolute coordinate by (-viewBoxMinX,
// -viewBoxMinY). Relative deltas (h-80, v240, c-1 2 3 4 5 6, etc.) stay as-is
// — deltas are invariant under translation.
//
// Naming convention (kebab-case filename → Kotlin identifier):
//   - `cart.svg`           → `FluxItIcons.Cart`
//   - `chevron-right.svg`  → `FluxItIcons.ChevronRight`
//   - `list-filled.svg`    → `FluxItIcons.ListFilled`
//
// Each icon is memoized via a top-level `private var _<lowerCamel>` backing
// field, mirroring the official Material Icons codegen pattern.

internal object KotlinIconEmitter {

    private const val PACKAGE = "dev.franzueto.fluxit.core.designsystem.icons"

    fun emit(icons: List<IconSource>): Map<String, String> = mapOf(
        "FluxItIcons.kt" to emitIcons(icons),
    )

    private fun emitIcons(icons: List<IconSource>): String = buildString {
        append(header())
        appendLine("import androidx.compose.ui.graphics.Color")
        appendLine("import androidx.compose.ui.graphics.SolidColor")
        appendLine("import androidx.compose.ui.graphics.vector.ImageVector")
        appendLine("import androidx.compose.ui.graphics.vector.path")
        appendLine("import androidx.compose.ui.unit.dp")
        appendLine()
        appendLine("public object FluxItIcons")
        val sorted = icons.sortedBy { identifierFor(it.name) }
        sorted.forEach { icon ->
            appendLine()
            appendIcon(icon)
        }
        appendLine()
        sorted.forEach { icon ->
            appendLine("private var _${backingFieldFor(icon.name)}: ImageVector? = null")
        }
    }

    private fun StringBuilder.appendIcon(icon: IconSource) {
        val id = identifierFor(icon.name)
        val backing = backingFieldFor(icon.name)
        appendLine("public val FluxItIcons.$id: ImageVector")
        appendLine("    get() {")
        appendLine("        _$backing?.let { return it }")
        appendLine("        return ImageVector.Builder(")
        appendLine("            name = \"FluxItIcons.$id\",")
        appendLine("            defaultWidth = 24.dp,")
        appendLine("            defaultHeight = 24.dp,")
        appendLine("            viewportWidth = ${floatLiteral(icon.viewBoxWidth)},")
        appendLine("            viewportHeight = ${floatLiteral(icon.viewBoxHeight)},")
        appendLine("        ).path(fill = SolidColor(Color.Black)) {")
        icon.commands.forEach { cmd ->
            appendLine("            ${pathCall(cmd, icon)}")
        }
        appendLine("        }.build().also { _$backing = it }")
        appendLine("    }")
    }

    private fun header(): String = """
        // AUTO-GENERATED by :core:core-designsystem:generateIcons — DO NOT EDIT.
        // Source of truth: core/core-designsystem/icons/*.svg.
        // See plan/02_DESIGN_SYSTEM.md §4 and ADR-005a.

        @file:Suppress(
            "MagicNumber",
            "MaxLineLength",
            "ktlint:standard:max-line-length",
            "ktlint:standard:multiline-expression-wrapping",
            "ktlint:standard:spacing-between-declarations-with-comments",
        )

        package $PACKAGE

    """.trimIndent()

    // ---- Path command → Compose builder call ---------------------------

    private fun pathCall(cmd: PathCommand, icon: IconSource): String {
        fun sx(v: Double) = floatLiteral(v - icon.viewBoxMinX)
        fun sy(v: Double) = floatLiteral(v - icon.viewBoxMinY)
        fun dx(v: Double) = floatLiteral(v)
        fun dy(v: Double) = floatLiteral(v)

        return when (cmd) {
            is MoveTo -> if (cmd.relative) "moveToRelative(${dx(cmd.x)}, ${dy(cmd.y)})" else "moveTo(${sx(cmd.x)}, ${sy(cmd.y)})"
            is LineTo -> if (cmd.relative) "lineToRelative(${dx(cmd.x)}, ${dy(cmd.y)})" else "lineTo(${sx(cmd.x)}, ${sy(cmd.y)})"
            is HorizontalLineTo -> if (cmd.relative) "horizontalLineToRelative(${dx(cmd.x)})" else "horizontalLineTo(${sx(cmd.x)})"
            is VerticalLineTo -> if (cmd.relative) "verticalLineToRelative(${dy(cmd.y)})" else "verticalLineTo(${sy(cmd.y)})"
            is CurveTo -> if (cmd.relative) {
                "curveToRelative(${dx(cmd.x1)}, ${dy(cmd.y1)}, ${dx(cmd.x2)}, ${dy(cmd.y2)}, ${dx(cmd.x)}, ${dy(cmd.y)})"
            } else {
                "curveTo(${sx(cmd.x1)}, ${sy(cmd.y1)}, ${sx(cmd.x2)}, ${sy(cmd.y2)}, ${sx(cmd.x)}, ${sy(cmd.y)})"
            }
            is ReflectiveCurveTo -> if (cmd.relative) {
                "reflectiveCurveToRelative(${dx(cmd.x2)}, ${dy(cmd.y2)}, ${dx(cmd.x)}, ${dy(cmd.y)})"
            } else {
                "reflectiveCurveTo(${sx(cmd.x2)}, ${sy(cmd.y2)}, ${sx(cmd.x)}, ${sy(cmd.y)})"
            }
            is QuadTo -> if (cmd.relative) {
                "quadToRelative(${dx(cmd.x1)}, ${dy(cmd.y1)}, ${dx(cmd.x)}, ${dy(cmd.y)})"
            } else {
                "quadTo(${sx(cmd.x1)}, ${sy(cmd.y1)}, ${sx(cmd.x)}, ${sy(cmd.y)})"
            }
            is ReflectiveQuadTo -> if (cmd.relative) "reflectiveQuadToRelative(${dx(cmd.x)}, ${dy(cmd.y)})" else "reflectiveQuadTo(${sx(cmd.x)}, ${sy(cmd.y)})"
            is Close -> "close()"
        }
    }

    // ---- Identifier mapping --------------------------------------------

    /** `chevron-right` → `ChevronRight`, `list-filled` → `ListFilled`, `cart` → `Cart`. */
    private fun identifierFor(filenameStem: String): String =
        filenameStem.split('-').joinToString("") { it.replaceFirstChar(Char::uppercaseChar) }

    /** `chevron-right` → `chevronRight`, used for the `_chevronRight` backing field. */
    private fun backingFieldFor(filenameStem: String): String {
        val pascal = identifierFor(filenameStem)
        return pascal.replaceFirstChar(Char::lowercaseChar)
    }

    // ---- Float literal formatting --------------------------------------

    private fun floatLiteral(v: Double): String =
        if (v == v.toLong().toDouble()) "${v.toLong()}f" else "${v}f"
}
