package dev.franzueto.fluxit.icons

// SwiftUI / xcassets emitter for the icon pipeline (ADR-005a).
//
// Unlike the token pipeline's SwiftEmitter (which emits a single .swift file),
// the icon pipeline outputs an xcassets *directory tree* plus a sibling Swift
// accessor file. The output is modeled as IconAssetCatalogOutput so the
// Gradle task in fluxit.designsystem.tokens.gradle.kts (extended in a
// follow-up commit) can mechanically write:
//
//   ios-app/Resources/FluxItIcons.xcassets/
//     Contents.json                                  ← root namespace metadata
//     ic-<name>.imageset/
//       Contents.json                                ← imageset metadata
//       ic-<name>.svg                                ← copy of source SVG
//   ios-app/Generated/FluxItIcons.swift              ← Swift accessors
//
// Why an `ic-` prefix on imageset names:
//   - Avoids collisions with future non-icon image assets (photos,
//     illustrations) that may end up in xcassets without confusion.
//   - Image name is decoupled from the Swift identifier — `cart.svg` →
//     imageset `ic-cart`, accessor `FluxItTokens.Icons.cart`.
//
// Why template-rendering-intent + preserves-vector-representation:
//   - `template` means SwiftUI's .foregroundStyle() tints the image as a
//     monochrome shape — mirrors Compose's `tint` parameter so call sites on
//     both platforms tint via the same mechanism.
//   - `preserves-vector-representation` keeps the SVG vector at render time
//     (no rasterization at design size) so the icons stay crisp when scaled.

internal object SwiftIconEmitter {

    private const val IMAGESET_PREFIX = "ic-"

    fun emit(icons: List<IconSource>): IconAssetCatalogOutput {
        val sorted = icons.sortedBy { it.name }
        return IconAssetCatalogOutput(
            xcassetsRootContentsJson = ROOT_CONTENTS_JSON,
            imagesets = sorted.map { icon ->
                val imagesetName = "$IMAGESET_PREFIX${icon.name}"
                ImageSetEntry(
                    imagesetName = imagesetName,
                    contentsJson = imagesetContentsJson(svgFilename = "$imagesetName.svg"),
                    sourceSvgFilename = "${icon.name}.svg",
                    outputSvgFilename = "$imagesetName.svg",
                )
            },
            swiftAccessorSource = emitSwiftAccessors(sorted),
        )
    }

    // ---- xcassets Contents.json bodies ---------------------------------

    private val ROOT_CONTENTS_JSON: String = """
        {
          "info" : {
            "author" : "xcode",
            "version" : 1
          }
        }
    """.trimIndent() + "\n"

    private fun imagesetContentsJson(svgFilename: String): String = """
        {
          "images" : [
            {
              "filename" : "$svgFilename",
              "idiom" : "universal"
            }
          ],
          "info" : {
            "author" : "xcode",
            "version" : 1
          },
          "properties" : {
            "preserves-vector-representation" : true,
            "template-rendering-intent" : "template"
          }
        }
    """.trimIndent() + "\n"

    // ---- Swift accessor source -----------------------------------------

    private fun emitSwiftAccessors(icons: List<IconSource>): String = buildString {
        appendLine("// AUTO-GENERATED by :core:core-designsystem:generateIcons — DO NOT EDIT.")
        appendLine("// Source of truth: core/core-designsystem/icons/*.svg.")
        appendLine("// See plan/02_DESIGN_SYSTEM.md §4 and ADR-005a.")
        appendLine()
        appendLine("import SwiftUI")
        appendLine()
        appendLine("public extension FluxItTokens {")
        appendLine("    enum Icons {")
        icons.forEach { icon ->
            val swiftId = swiftIdentifier(icon.name)
            val imageName = "$IMAGESET_PREFIX${icon.name}"
            appendLine("        public static let $swiftId: Image = Image(\"$imageName\")")
        }
        appendLine("    }")
        appendLine("}")
    }

    // ---- Identifier mapping --------------------------------------------

    /** `chevron-right` → `chevronRight`, `list-filled` → `listFilled`, `cart` → `cart`. */
    private fun swiftIdentifier(filenameStem: String): String {
        val parts = filenameStem.split('-')
        if (parts.isEmpty()) return filenameStem
        return parts.first() + parts.drop(1).joinToString("") {
            it.replaceFirstChar(Char::uppercaseChar)
        }
    }
}

/** Output of the SwiftUI / xcassets icon emitter. Modeled as a tree because
 *  xcassets is a directory bundle, not a single text file. */
internal data class IconAssetCatalogOutput(
    val xcassetsRootContentsJson: String,
    val imagesets: List<ImageSetEntry>,
    val swiftAccessorSource: String,
)

/** One xcassets imageset entry. */
internal data class ImageSetEntry(
    /** e.g. "ic-cart". The directory written is "<imagesetName>.imageset/". */
    val imagesetName: String,
    /** Imageset Contents.json body. */
    val contentsJson: String,
    /** Source SVG filename inside core/core-designsystem/icons/ (e.g. "cart.svg"). */
    val sourceSvgFilename: String,
    /** Output SVG filename inside the imageset (e.g. "ic-cart.svg"). */
    val outputSvgFilename: String,
)
