package dev.franzueto.fluxit.tokens

// Compose / Kotlin emitter for the design-token pipeline (ADR-005).
//
// Returns generated-file basename → full source text. The Gradle task in
// fluxit.designsystem.tokens.gradle.kts writes the result to
// core-designsystem/build/generated/source/tokens/androidMain/ and registers
// that directory on the androidMain Kotlin source set.
//
// The output references types from Jetpack Compose (Color, Dp, TextStyle,
// FontFamily, RoundedCornerShape) — these live in androidx.compose.ui.*, so
// the generated files compile only on Android. iOS gets its own emitter
// (SwiftEmitter, next commit).
//
// Naming convention (DTCG path → Kotlin property name):
//   - Drop theme prefix (`dark.` / `light.`) and category prefix
//     (`color.`, `typography.`, `elevation.`, `spacing.`, `shape.`).
//   - Camel-case the remaining segments. Example:
//     `dark.color.surface.cardMuted` → `surfaceCardMuted`.
//   - For `spacing.scale.xs` etc., the leading `scale` segment is kept
//     to disambiguate from shape/dimension names of the same final segment.

internal object KotlinEmitter {

    private const val PACKAGE = "dev.franzueto.fluxit.core.designsystem.tokens"

    fun emit(doc: TokenDocument): Map<String, String> = mapOf(
        "FluxItColors.kt" to emitColors(doc),
        "FluxItSpacing.kt" to emitSpacing(doc),
        "FluxItShapes.kt" to emitShapes(doc),
        "FluxItTypography.kt" to emitTypography(doc),
        "FluxItElevation.kt" to emitElevation(doc),
    )

    private fun header(): String = """
        // AUTO-GENERATED by :core:core-designsystem:generateTokens — DO NOT EDIT.
        // Source of truth: core/core-designsystem/tokens/tokens.json.
        // See plan/02_DESIGN_SYSTEM.md §1 and ADR-005.

        @file:Suppress("MagicNumber", "MaxLineLength", "ktlint:standard:max-line-length")

        package $PACKAGE

    """.trimIndent()

    private fun emitColors(doc: TokenDocument): String = buildString {
        append(header())
        appendLine("import androidx.compose.ui.graphics.Color")
        appendLine()
        appendLine("public object FluxItColors {")
        // Stable ordering: by flattened property name.
        doc.colors.sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /** ${escapeKDoc(it)} */") }
            appendLine("    public val ${propertyName(tok.path)}: Color = ${colorLiteral(tok.color)}")
        }
        appendLine("}")
    }

    private fun emitSpacing(doc: TokenDocument): String = buildString {
        append(header())
        appendLine("import androidx.compose.ui.unit.Dp")
        appendLine("import androidx.compose.ui.unit.dp")
        appendLine()
        appendLine("public object FluxItSpacing {")
        spacingTokens(doc).sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /** ${escapeKDoc(it)} */") }
            appendLine("    public val ${propertyName(tok.path)}: Dp = ${dpLiteral(tok.px)}")
        }
        appendLine("}")
    }

    private fun emitShapes(doc: TokenDocument): String = buildString {
        append(header())
        appendLine("import androidx.compose.foundation.shape.RoundedCornerShape")
        appendLine("import androidx.compose.ui.graphics.Shape")
        appendLine()
        appendLine("public object FluxItShapes {")
        shapeTokens(doc).sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /** ${escapeKDoc(it)} */") }
            appendLine("    public val ${propertyName(tok.path)}: Shape = RoundedCornerShape(${dpLiteral(tok.px)})")
        }
        appendLine("}")
    }

    private fun emitTypography(doc: TokenDocument): String = buildString {
        append(header())
        appendLine("import androidx.compose.ui.text.TextStyle")
        appendLine("import androidx.compose.ui.text.font.FontFamily")
        appendLine("import androidx.compose.ui.text.font.FontWeight")
        appendLine("import androidx.compose.ui.unit.em")
        appendLine("import androidx.compose.ui.unit.sp")
        appendLine()
        appendLine("// FontFamily.SansSerif is a temporary stand-in. Phase 02 §3 bundles")
        appendLine("// Inter-Variable.ttf as a real FontFamily and replaces this reference.")
        appendLine("private val DefaultFamily: FontFamily = FontFamily.SansSerif")
        appendLine()
        appendLine("public object FluxItTypography {")
        doc.typography.sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /** ${escapeKDoc(it)} */") }
            appendLine("    public val ${propertyName(tok.path)}: TextStyle = TextStyle(")
            appendLine("        fontFamily = DefaultFamily,")
            appendLine("        fontWeight = FontWeight(${tok.fontWeight}),")
            appendLine("        fontSize = ${dpLiteral(tok.fontSizePx).replace(".dp", ".sp")},")
            appendLine("        lineHeight = ${formatDouble(tok.lineHeight)}.em,")
            tok.letterSpacingEm?.let {
                appendLine("        letterSpacing = ${formatDouble(it)}.em,")
            }
            appendLine("    )")
        }
        appendLine("}")
    }

    private fun emitElevation(doc: TokenDocument): String = buildString {
        append(header())
        appendLine("import androidx.compose.ui.graphics.Color")
        appendLine("import androidx.compose.ui.unit.Dp")
        appendLine("import androidx.compose.ui.unit.dp")
        appendLine()
        appendLine("public data class FluxItElevationValue(")
        appendLine("    public val color: Color,")
        appendLine("    public val offsetX: Dp,")
        appendLine("    public val offsetY: Dp,")
        appendLine("    public val blur: Dp,")
        appendLine("    public val spread: Dp,")
        appendLine(")")
        appendLine()
        appendLine("public object FluxItElevation {")
        doc.shadows.sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /** ${escapeKDoc(it)} */") }
            appendLine("    public val ${propertyName(tok.path)}: FluxItElevationValue = FluxItElevationValue(")
            appendLine("        color = ${colorLiteral(tok.color)},")
            appendLine("        offsetX = ${dpLiteral(tok.offsetXPx)},")
            appendLine("        offsetY = ${dpLiteral(tok.offsetYPx)},")
            appendLine("        blur = ${dpLiteral(tok.blurPx)},")
            appendLine("        spread = ${dpLiteral(tok.spreadPx)},")
            appendLine("    )")
        }
        appendLine("}")
    }

    // ---- Path → identifier ------------------------------------------------

    private fun propertyName(path: List<String>): String {
        // Drop theme prefix and category prefix.
        val themesAndCategories = setOf(
            "light", "dark", "color", "typography", "shape", "spacing", "elevation",
        )
        val segments = path.dropWhile { it in themesAndCategories }
        require(segments.isNotEmpty()) {
            "Token at `${path.joinToString(".")}` flattens to empty identifier — every token needs at least one path segment beyond its theme/category."
        }
        return segments.first().decapitalizeFirst() + segments.drop(1).joinToString("") { it.capitalizeFirst() }
    }

    private fun String.capitalizeFirst(): String =
        if (isEmpty()) this else this[0].uppercaseChar() + substring(1)

    private fun String.decapitalizeFirst(): String =
        if (isEmpty()) this else this[0].lowercaseChar() + substring(1)

    // ---- Literal formatting -----------------------------------------------

    private fun colorLiteral(c: Rgba): String {
        // Compose Color(0xAARRGGBB).
        val argb = (c.a shl 24) or (c.r shl 16) or (c.g shl 8) or c.b
        val hex = "%08X".format(argb.toLong() and 0xFFFFFFFFL)
        return "Color(0x$hex)"
    }

    private fun dpLiteral(px: Double): String = "${formatDouble(px)}.dp"

    private fun formatDouble(v: Double): String =
        if (v == v.toLong().toDouble()) v.toLong().toString() else v.toString()

    private fun escapeKDoc(s: String): String =
        s.replace("*/", "*\\/")

    // ---- Category filtering -----------------------------------------------

    private fun spacingTokens(doc: TokenDocument): List<DimensionToken> =
        doc.dimensions.filter { it.path.firstOrNull() == "spacing" }

    private fun shapeTokens(doc: TokenDocument): List<DimensionToken> =
        doc.dimensions.filter { it.path.firstOrNull() == "shape" }
}
