package dev.franzueto.fluxit.tokens

// SwiftUI emitter for the design-token pipeline (ADR-005).
//
// Produces a SINGLE file `FluxItTokens.swift` that nests every category under
// the top-level enum `FluxItTokens`. The Gradle task writes the file to
// ios-app/Generated/FluxItTokens.swift (gitignored; xcodegen's project.yml
// globs Generated/**.swift on the next scripts/build-ios.sh).
//
// Notable differences from KotlinEmitter:
//   - The outer namespace is `FluxItTokens` (per plan/02_DESIGN_SYSTEM.md §1).
//     Inner sub-namespaces are plural (Colors, Shapes) to avoid colliding with
//     SwiftUI types (Color, Shape).
//   - SwiftUI `Font` can't carry lineHeight or letterSpacing, so typography
//     emits a `TypographyStyle` struct (font + lineHeight + tracking).
//   - Shape tokens emit as `CGFloat` corner radii (SwiftUI has no `Shape`
//     instance equivalent to Compose's `RoundedCornerShape`); call sites use
//     `.cornerRadius(FluxItTokens.Shapes.md)` or
//     `RoundedRectangle(cornerRadius: FluxItTokens.Shapes.md)`.
//   - letterSpacing is converted to points (em × fontSize) at generation time
//     because SwiftUI's `.tracking(_:)` takes CGFloat in points.
//   - Inter is stubbed via `Font.system(...)` until Phase 02 §3 bundles
//     Inter-Variable.ttf, mirroring the Compose side.

internal object SwiftEmitter {

    fun emit(doc: TokenDocument): Map<String, String> = mapOf(
        "FluxItTokens.swift" to emitAll(doc),
    )

    private fun emitAll(doc: TokenDocument): String = buildString {
        appendLine("// AUTO-GENERATED by :core:core-designsystem:generateTokens — DO NOT EDIT.")
        appendLine("// Source of truth: core/core-designsystem/tokens/tokens.json.")
        appendLine("// See plan/02_DESIGN_SYSTEM.md §1 and ADR-005.")
        appendLine()
        appendLine("import SwiftUI")
        appendLine()
        appendLine("public enum FluxItTokens {")
        appendLine()
        appendBlock(emitColors(doc))
        appendLine()
        appendBlock(emitSpacing(doc))
        appendLine()
        appendBlock(emitShapes(doc))
        appendLine()
        appendBlock(emitTypography(doc))
        appendLine()
        appendBlock(emitElevation(doc))
        appendLine("}")
    }

    private fun StringBuilder.appendBlock(body: String) {
        body.lineSequence().forEach { line ->
            if (line.isEmpty()) appendLine() else appendLine("    $line")
        }
    }

    private fun emitColors(doc: TokenDocument): String = buildString {
        appendLine("public enum Colors {")
        doc.colors.sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /// ${escapeDocLine(it)}") }
            appendLine("    public static let ${propertyName(tok.path)}: Color = ${colorLiteral(tok.color)}")
        }
        appendLine("}")
    }

    private fun emitSpacing(doc: TokenDocument): String = buildString {
        appendLine("public enum Spacing {")
        doc.dimensions.filter { it.path.firstOrNull() == "spacing" }
            .sortedBy { propertyName(it.path) }
            .forEach { tok ->
                tok.description?.let { appendLine("    /// ${escapeDocLine(it)}") }
                appendLine("    public static let ${propertyName(tok.path)}: CGFloat = ${cgFloatLiteral(tok.px)}")
            }
        appendLine("}")
    }

    private fun emitShapes(doc: TokenDocument): String = buildString {
        appendLine("public enum Shapes {")
        appendLine("    // CGFloat corner radii. Use with .cornerRadius(FluxItTokens.Shapes.md) or")
        appendLine("    // RoundedRectangle(cornerRadius: FluxItTokens.Shapes.md).")
        doc.dimensions.filter { it.path.firstOrNull() == "shape" }
            .sortedBy { propertyName(it.path) }
            .forEach { tok ->
                tok.description?.let { appendLine("    /// ${escapeDocLine(it)}") }
                appendLine("    public static let ${propertyName(tok.path)}: CGFloat = ${cgFloatLiteral(tok.px)}")
            }
        appendLine("}")
    }

    private fun emitTypography(doc: TokenDocument): String = buildString {
        appendLine("public struct TypographyStyle {")
        appendLine("    public let font: Font")
        appendLine("    public let lineHeight: CGFloat   // unitless multiplier of fontSize")
        appendLine("    public let tracking: CGFloat     // letter-spacing in points")
        appendLine("}")
        appendLine()
        appendLine("// Font.system is a temporary stand-in. Phase 02 §3 bundles Inter-Variable.ttf")
        appendLine("// and replaces these with `.custom(\"Inter\", size: …)` calls.")
        appendLine("public enum Typography {")
        doc.typography.sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /// ${escapeDocLine(it)}") }
            val trackingPt = (tok.letterSpacingEm ?: 0.0) * tok.fontSizePx
            appendLine("    public static let ${propertyName(tok.path)} = TypographyStyle(")
            appendLine("        font: .system(size: ${cgFloatLiteral(tok.fontSizePx)}, weight: ${swiftFontWeight(tok.fontWeight)}),")
            appendLine("        lineHeight: ${cgFloatLiteral(tok.lineHeight)},")
            appendLine("        tracking: ${cgFloatLiteral(trackingPt)}")
            appendLine("    )")
        }
        appendLine("}")
    }

    private fun emitElevation(doc: TokenDocument): String = buildString {
        appendLine("public struct ElevationValue {")
        appendLine("    public let color: Color")
        appendLine("    public let offsetX: CGFloat")
        appendLine("    public let offsetY: CGFloat")
        appendLine("    public let blur: CGFloat")
        appendLine("    public let spread: CGFloat")
        appendLine("}")
        appendLine()
        appendLine("public enum Elevation {")
        doc.shadows.sortedBy { propertyName(it.path) }.forEach { tok ->
            tok.description?.let { appendLine("    /// ${escapeDocLine(it)}") }
            appendLine("    public static let ${propertyName(tok.path)} = ElevationValue(")
            appendLine("        color: ${colorLiteral(tok.color)},")
            appendLine("        offsetX: ${cgFloatLiteral(tok.offsetXPx)},")
            appendLine("        offsetY: ${cgFloatLiteral(tok.offsetYPx)},")
            appendLine("        blur: ${cgFloatLiteral(tok.blurPx)},")
            appendLine("        spread: ${cgFloatLiteral(tok.spreadPx)}")
            appendLine("    )")
        }
        appendLine("}")
    }

    // ---- Path → identifier (must stay identical to KotlinEmitter) --------

    private fun propertyName(path: List<String>): String {
        val themesAndCategories = setOf(
            "light", "dark", "color", "typography", "shape", "spacing", "elevation",
        )
        val segments = path.dropWhile { it in themesAndCategories }
        require(segments.isNotEmpty()) {
            "Token at `${path.joinToString(".")}` flattens to empty identifier."
        }
        return segments.first().decapitalizeFirst() + segments.drop(1).joinToString("") { it.capitalizeFirst() }
    }

    private fun String.capitalizeFirst(): String =
        if (isEmpty()) this else this[0].uppercaseChar() + substring(1)

    private fun String.decapitalizeFirst(): String =
        if (isEmpty()) this else this[0].lowercaseChar() + substring(1)

    // ---- Literal formatting ----------------------------------------------

    private fun colorLiteral(c: Rgba): String {
        val r = c.r.toDouble() / 255.0
        val g = c.g.toDouble() / 255.0
        val b = c.b.toDouble() / 255.0
        val a = c.a.toDouble() / 255.0
        return "Color(.sRGB, red: ${swiftDouble(r)}, green: ${swiftDouble(g)}, blue: ${swiftDouble(b)}, opacity: ${swiftDouble(a)})"
    }

    private fun cgFloatLiteral(v: Double): String =
        if (v == v.toLong().toDouble()) v.toLong().toString() else swiftDouble(v)

    /** Trims long fractional Double tails to 6 significant decimal places. */
    private fun swiftDouble(v: Double): String {
        if (v == v.toLong().toDouble()) return "${v.toLong()}.0"
        val rounded = "%.6f".format(v).trimEnd('0').trimEnd('.')
        return if ('.' in rounded) rounded else "$rounded.0"
    }

    private fun swiftFontWeight(w: Int): String = when {
        w <= 100 -> ".ultraLight"
        w <= 200 -> ".thin"
        w <= 300 -> ".light"
        w <= 400 -> ".regular"
        w <= 500 -> ".medium"
        w <= 600 -> ".semibold"
        w <= 700 -> ".bold"
        w <= 800 -> ".heavy"
        else -> ".black"
    }

    private fun escapeDocLine(s: String): String = s.replace("\n", " ")
}
