package com.fluxit.firebase

import android.content.Context
import com.fluxit.config.FirebaseEmulatorConfig
import com.google.firebase.FirebaseApp
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.storage.FirebaseStorage

/**
 * initialization seam for the official Firebase Android SDK.
 *
 * This is deliberately the only place in `androidMain` that touches Firebase SDK
 * types for initialization and emulator wiring. Nothing here is exposed to `commonMain`; the
 * shared code only ever sees the plain-constant [FirebaseEmulatorConfig] object generated by
 * the `:composeApp:generateFirebaseEmulatorConfig` Gradle task.
 */
object AndroidFirebaseInitializer {

    /**
     * Host alias the Android emulator uses to reach the development machine's
     * loopback interface. A physical device cannot reach the host that way, so a
     * device developer must set `fluxit.firebase.emulator.host` to the machine's
     * LAN address explicitly.
     */
    private const val ANDROID_EMULATOR_HOST_LOOPBACK_ALIAS = "10.0.2.2"

    private var initialized = false

    /**
     * Initializes the default [FirebaseApp] from `composeApp/google-services.json`
     * (gitignored, per the gitignored-config policy) and, when the emulator override is switched on,
     * points Auth/Firestore/Storage at the local emulator suite.
     *
     * Must run before anything else touches the Firebase SDK, because
     * `useEmulator` may only be called before a service instance is used.
     */
    @Synchronized
    fun initialize(context: Context) {
        if (initialized) return
        initialized = true

        checkNotNull(FirebaseApp.initializeApp(context.applicationContext)) {
            "Firebase default app could not be initialized. composeApp/google-services.json " +
                "is missing or invalid; fetch it from the Firebase Console (it is gitignored)."
        }

        if (FirebaseEmulatorConfig.ENABLED) {
            connectToEmulators()
        }
    }

    private fun connectToEmulators() {
        val host = resolveEmulatorHost(FirebaseEmulatorConfig.HOST)
        FirebaseAuth.getInstance().useEmulator(host, FirebaseEmulatorConfig.AUTH_PORT)
        FirebaseFirestore.getInstance().useEmulator(host, FirebaseEmulatorConfig.FIRESTORE_PORT)
        FirebaseStorage.getInstance().useEmulator(host, FirebaseEmulatorConfig.STORAGE_PORT)
    }

    private fun resolveEmulatorHost(configuredHost: String): String =
        when (configuredHost) {
            "127.0.0.1", "localhost" -> ANDROID_EMULATOR_HOST_LOOPBACK_ALIAS
            else -> configuredHost
        }
}
