import ComposeApp
import FirebaseAuth
import FirebaseCore
import FirebaseFirestore
import FirebaseStorage
import UIKit

/// FB-007 initialization seam for the official Firebase Apple SDK.
///
/// This is deliberately the only place in the iOS app that touches Firebase SDK
/// types during Phase 0. It mirrors `AndroidFirebaseInitializer` in `androidMain`:
/// configure the default app, then - only when the build enabled it - point
/// Auth/Firestore/Storage at the local emulator suite.
///
/// The Apple SDK is integrated through Swift Package Manager into the Xcode
/// project rather than through Kotlin/Native cinterop, because `FirebaseStorage`
/// and the modern `FirebaseAuth` are Swift modules that cinterop cannot consume.
/// The emulator endpoints still come from the single shared source of truth: the
/// `FirebaseEmulatorConfig` constants generated by
/// `:composeApp:generateFirebaseEmulatorConfig`, surfaced to Swift through
/// `IosFirebaseEmulatorSettings` in `iosMain`.
///
/// `FB-103` added the second responsibility below: registering the Swift
/// implementation of the Kotlin `IosAuthBridge` protocol, which is how the
/// Firebase-neutral `AuthRepository` reaches Auth on iOS (PLAN-008). `FB-203` does the
/// same for `ListRepository`/Firestore lists, `FB-205` for `ItemRepository`/Firestore
/// items, and `FB-305` for `PhotoStorage`/Storage photos.
enum FirebaseBootstrap {

    private static var initialized = false

    /// Initializes the default `FirebaseApp` from the bundled
    /// `GoogleService-Info.plist` (gitignored, per `DEC-002b`).
    ///
    /// Must run before anything else touches the Firebase SDK, because
    /// `useEmulator` may only be called before a service instance is used.
    /// `AppDelegate.application(_:didFinishLaunchingWithOptions:)` is the earliest
    /// point the system gives us and runs strictly before any SwiftUI scene or
    /// view body - and therefore before `ContentView` creates the Compose view
    /// controller that starts Koin.
    static func start() {
        guard !initialized else { return }
        initialized = true

        guard FirebaseOptions.defaultOptions() != nil else {
            fatalError(
                "Firebase default app could not be initialized. "
                + "iosApp/GoogleService-Info.plist is missing from the app bundle; "
                + "fetch it from the Firebase Console (it is gitignored)."
            )
        }
        FirebaseApp.configure()

        if IosFirebaseEmulatorSettings.shared.enabled {
            connectToEmulators()
        }

        // FB-103: hand the Swift Auth implementation to the Kotlin framework. This runs
        // inside `didFinishLaunchingWithOptions`, strictly before `ContentView` creates
        // the Compose view controller that starts Koin, so the `single<AuthRepository>`
        // binding in `platformModule()` can never be resolved before the bridge exists.
        IosAuthBridgeRegistry.shared.register(bridge: FirebaseAuthBridge())

        // FB-203: same hand-off, for the Firestore list bridge.
        IosFirestoreListBridgeRegistry.shared.register(bridge: FirebaseListBridge())

        // FB-205: same hand-off, for the Firestore item bridge.
        IosFirestoreItemBridgeRegistry.shared.register(bridge: FirebaseItemBridge())

        // FB-305: same hand-off, for the Storage photo bridge.
        let storageBridge = FirebaseStorageBridge()
        IosFirebaseStorageBridgeRegistry.shared.register(bridge: storageBridge)
        IosSessionCleanupBridgeRegistry.shared.register(bridge: FirebaseSessionCleanupBridge(storageBridge: storageBridge))
    }

    #if FLUXIT_PARITY
    // FB-703: opt-in build symbol + emulator-only Kotlin gate + explicit launch argument.
    static func runFirebaseRegressionIfRequested() {
        let arguments = ProcessInfo.processInfo.arguments
        guard arguments.contains("-FluxItFirebaseRegressionSelfCheck"), IosFirebaseEmulatorSettings.shared.enabled else { return }
        func value(_ key: String) -> String? {
            guard let index = arguments.firstIndex(of: key), index + 1 < arguments.count else { return nil }
            return arguments[index + 1]
        }
        guard let email = value("-parityEmail"), let password = value("-parityPassword"),
              let marker = value("-parityMarker") else { print("FB-703 iOS FAILED missing-arguments\nFB-703 END"); return }
        Task {
            do {
                let offline = try await IosFirebaseRegressionCheck.shared.runOffline(email: email, password: password, marker: marker, disconnect: { completion in
                    Firestore.firestore().disableNetwork { error in completion(KotlinBoolean(value: error == nil)) }
                }, reconnect: {
                    Task { try await Firestore.firestore().enableNetwork() }
                })
                print(offline)
                guard offline.contains("offline PASS") else { print("FB-703 iOS FAILED\nFB-703 END"); return }
                print(try await IosFirebaseRegressionCheck.shared.run(email: email, password: password, marker: marker))
            } catch {
                try? await Firestore.firestore().enableNetwork()
                print("FB-703 iOS FAILED\nFB-703 END")
            }
        }
    }
    #endif

    #if FLUXIT_PARITY
    /// FB-103 evidence hook: runs the emulator-backed Auth integration check and prints
    /// its report, then leaves the app running normally.
    ///
    /// FLUXIT_PARITY compiles this hook only with the opt-in Kotlin fixture. Runtime
    /// gates also require the launch argument and emulator configuration: the app must be
    /// launched with `-FluxItAuthSelfCheck`, and the Kotlin check itself refuses to run
    /// unless the build was configured with `fluxit.firebase.emulator.enabled=true`,
    /// which is the same flag that points Auth at the local emulator. It therefore
    /// cannot touch the live development project.
    static func runAuthSelfCheckIfRequested() {
        let arguments = ProcessInfo.processInfo.arguments
        let restorationPhase = arguments.contains("-FluxItAuthRestorePrepare") ? "prepare"
            : arguments.contains("-FluxItAuthRestoreVerify") ? "verify"
            : nil

        guard arguments.contains("-FluxItAuthSelfCheck") || restorationPhase != nil else { return }

        Task {
            do {
                let report: String
                if let phase = restorationPhase {
                    report = try await IosAuthIntegrationCheck.shared.runRestorationPhase(phase: phase)
                } else {
                    report = try await IosAuthIntegrationCheck.shared.run()
                }
                print(report)
            } catch {
                print("FB-103 iOS Auth integration check: THREW \(error)")
                print("FB-103 END")
            }
        }
    }

    #endif

    #if FLUXIT_PARITY
    /// FB-203 evidence hook: same shape as [runAuthSelfCheckIfRequested], for the
    /// Firestore list adapter. Guarded the same way: `-FluxItFirestoreListSelfCheck` on
    /// the launch arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runFirestoreListSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItFirestoreListSelfCheck") else { return }

        Task {
            do {
                let report = try await IosFirestoreListIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-203 iOS Firestore list integration check: THREW \(error)")
                print("FB-203 END")
            }
        }
    }

    /// FB-205 evidence hook: same shape as [runFirestoreListSelfCheckIfRequested], for
    /// the Firestore item adapter. Guarded the same way: `-FluxItFirestoreItemSelfCheck`
    /// on the launch arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runFirestoreItemSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItFirestoreItemSelfCheck") else { return }

        Task {
            do {
                let report = try await IosFirestoreItemIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-205 iOS Firestore item integration check: THREW \(error)")
                print("FB-205 END")
            }
        }
    }

    /// FB-206 evidence hook: same shape as [runFirestoreItemSelfCheckIfRequested], for
    /// the cross-client counter-consistency/conflict/malformed-document/reconnect
    /// checks. Guarded the same way: `-FluxItCrossClientSelfCheck` on the launch
    /// arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runCrossClientSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItCrossClientSelfCheck") else { return }

        Task {
            do {
                let report = try await IosFirestoreCrossClientIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-206 iOS cross-client integration check: THREW \(error)")
                print("FB-206 END")
            }
        }
    }

    /// FB-305 evidence hook: same shape as [runFirestoreItemSelfCheckIfRequested], for the
    /// Storage photo adapter. Guarded the same way: `-FluxItPhotoStorageSelfCheck` on the
    /// launch arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runPhotoStorageSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageSelfCheck") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-305 iOS Storage integration check: THREW \(error)")
                print("FB-305 END")
            }
        }
    }

    /// `FB-307` evidence hook: interrupted-replace/orphan-detection/retry-recovery check.
    /// Guarded the same way: `-FluxItPhotoStorageInterruptedReplaceCheck` on the launch
    /// arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runPhotoStorageInterruptedReplaceCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageInterruptedReplaceCheck") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.runInterruptedReplaceCheck()
                print(report)
            } catch {
                print("FB-307 iOS Storage interrupted-replace check: THREW \(error)")
                print("FB-307 END")
            }
        }
    }

    /// `FB-307` evidence hook: the publish half of the cross-device/reinstall check pair.
    /// Guarded by `-FluxItPhotoStorageCrossDevicePublish` on the launch arguments, plus
    /// the Kotlin check's own emulator-enabled refusal. See
    /// `IosPhotoStorageIntegrationCheck`'s class KDoc for how to combine this with
    /// `runPhotoStorageCrossDeviceSubscribeIfRequested` for either a cross-device or a
    /// literal-reinstall run.
    static func runPhotoStorageCrossDevicePublishIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageCrossDevicePublish") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.runCrossDevicePublish()
                print(report)
            } catch {
                print("FB-307 iOS Storage cross-device publish check: THREW \(error)")
                print("FB-307 END")
            }
        }
    }

    /// `FB-307` evidence hook: the subscribe half of the cross-device/reinstall check
    /// pair. Guarded by `-FluxItPhotoStorageCrossDeviceSubscribe` on the launch
    /// arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runPhotoStorageCrossDeviceSubscribeIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageCrossDeviceSubscribe") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.runCrossDeviceSubscribe()
                print(report)
            } catch {
                print("FB-307 iOS Storage cross-device subscribe check: THREW \(error)")
                print("FB-307 END")
            }
        }
    }

    /// `FB-408` evidence hook: live pre-fix/post-fix reproduction of `FB-405`'s headline
    /// finding (a terminal Firestore listener error crashing the app process). Guarded the
    /// same way: `-FluxItDashboardListenerCrashSelfCheck` on the launch arguments, plus the
    /// Kotlin check's own emulator-enabled refusal. See
    /// `IosDashboardListenerCrashSelfCheck`'s KDoc for why this check's own try/catch here
    /// cannot mask the crash it exists to reproduce - that crash happens on a separate,
    /// unstructured `viewModelScope` coroutine, not on this `Task`'s own call stack.
    static func runDashboardListenerCrashSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItDashboardListenerCrashSelfCheck") else { return }

        Task {
            do {
                let report = try await IosDashboardListenerCrashSelfCheck.shared.run()
                print(report)
            } catch {
                print("FB-408 iOS listener-crash self-check: THREW \(error)")
                print("FB-408 END")
            }
        }
    }
    #endif

    private static func connectToEmulators() {
        // Passed through verbatim: the iOS simulator shares the host network stack,
        // so no Android-style 10.0.2.2 loopback translation applies here.
        let settings = IosFirebaseEmulatorSettings.shared
        let host = settings.host

        Auth.auth().useEmulator(withHost: host, port: Int(settings.authPort))

        // FB-203: `useEmulator(withHost:port:)` alone was empirically found NOT to
        // disable TLS reliably for this SDK version's gRPC transport when first
        // genuinely exercised (Firestore emulator work was unexercised on iOS through
        // FB-007/FB-008/FB-202) - the client kept attempting a TLS handshake against the
        // plaintext local emulator (`SSL_ERROR_SSL ... WRONG_VERSION_NUMBER`, confirmed
        // against a real emulator that answers plain HTTP on the same port). Setting
        // `isSSLEnabled = false` explicitly on the `FirestoreSettings` - the older,
        // lower-level documented pattern `useEmulator` is meant to be sugar for - is a
        // deliberate belt-and-suspenders fix, not a style preference. `useEmulator` is
        // still called first so a future SDK fix keeps working the documented way; must
        // still run before the first `Firestore` operation or the SDK throws.
        let firestore = Firestore.firestore()
        firestore.useEmulator(withHost: host, port: Int(settings.firestorePort))
        let firestoreSettings = firestore.settings
        firestoreSettings.isSSLEnabled = false
        firestore.settings = firestoreSettings

        Storage.storage().useEmulator(withHost: host, port: Int(settings.storagePort))
    }
}

/// Minimal application delegate whose only job is to give `FirebaseApp.configure()`
/// a deterministic home. `iOSApp.swift` is a bare SwiftUI `@main` with no delegate,
/// so this is attached via `@UIApplicationDelegateAdaptor`. Firebase documents this
/// as the SwiftUI integration point, and later Firebase features that need UIKit
/// app-lifecycle callbacks (push notifications, phone auth) already have a home here.
final class AppDelegate: NSObject, UIApplicationDelegate {
    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
    ) -> Bool {
        FirebaseBootstrap.start()
        #if FLUXIT_PARITY
        if ProcessInfo.processInfo.arguments.contains("-FluxItDefaultGraphCheck") {
            // Resolve the real startup graph without mounting Compose or restoring auth.
            precondition(!IosFirebaseEmulatorSettings.shared.enabled)
            precondition(Firestore.firestore().settings.isSSLEnabled)
            precondition(Firestore.firestore().settings.host == "firestore.googleapis.com")
            print(IosDefaultGraphCheck.shared.run())
            return true
        }
        if FirebaseBootstrap.runSessionCleanupIfRequested() { return true }
        FirebaseBootstrap.runFirebaseRegressionIfRequested()
        #endif
        #if FLUXIT_PARITY
        FirebaseBootstrap.runAuthSelfCheckIfRequested()
        FirebaseBootstrap.runFirestoreListSelfCheckIfRequested()
        FirebaseBootstrap.runFirestoreItemSelfCheckIfRequested()
        FirebaseBootstrap.runCrossClientSelfCheckIfRequested()
        FirebaseBootstrap.runPhotoStorageSelfCheckIfRequested()
        FirebaseBootstrap.runPhotoStorageInterruptedReplaceCheckIfRequested()
        FirebaseBootstrap.runPhotoStorageCrossDevicePublishIfRequested()
        FirebaseBootstrap.runPhotoStorageCrossDeviceSubscribeIfRequested()
        FirebaseBootstrap.runDashboardListenerCrashSelfCheckIfRequested()
        #endif
        return true
    }
}

/// Local privacy lifecycle; all SDK objects remain on the Swift side of the boundary.
final class FirebaseSessionCleanupBridge: NSObject, IosSessionCleanupBridge {
    private let storageBridge: FirebaseStorageBridge
    private var cleanupTask: Task<Void, Error>?
    private var stopped: Firestore?
    private var terminated = false
    private var savedSettings: FirestoreSettings?
    private let defaults: UserDefaults
    private var startupRecovery: Bool

    init(storageBridge: FirebaseStorageBridge, defaults: UserDefaults = .standard) {
        self.storageBridge = storageBridge
        self.defaults = defaults
        self.startupRecovery = defaults.bool(forKey: "session-cleanup-pending")
        super.init()
    }

    var pending: Bool { defaults.bool(forKey: "session-cleanup-pending") }
    func begin_() -> Bool {
        defaults.set(true, forKey: "session-cleanup-pending")
        return defaults.synchronize()
    }
    func complete_() -> Bool {
        defaults.removeObject(forKey: "session-cleanup-pending")
        cleanupTask = nil
        return defaults.synchronize()
    }

    func clear(completion: @escaping ((any Error)?) -> Void) {
        // Calls arrive on the Kotlin main dispatcher. Retain one operation through
        // UI timeout, so a retry cannot race an SDK termination still completing.
        if cleanupTask == nil {
            cleanupTask = Task { @MainActor in
                await storageBridge.cancelSessionTasks()
                let old = stopped ?? Firestore.firestore()
                if stopped == nil { savedSettings = old.settings; stopped = old }
                // Avoid initializing a network client with old persisted writes on restart.
                if startupRecovery {
                    do { try await old.clearPersistence() }
                    catch {
                        let failure = error as NSError
                        guard failure.domain == FirestoreErrorDomain && failure.code == FirestoreErrorCode.failedPrecondition.rawValue else { throw error }
                    }
                    startupRecovery = false
                }
                if !terminated { try await old.terminate(); terminated = true }
                try await old.clearPersistence()
                let fresh = Firestore.firestore()
                guard fresh !== old, let settings = savedSettings else {
                    throw NSError(domain: "SessionCleanup", code: 1)
                }
                fresh.settings = settings
                stopped = nil
                terminated = false
                savedSettings = nil
            }
        }
        let task = cleanupTask!
        Task { @MainActor in
            do { try await task.value; completion(nil) }
            catch {
                cleanupTask = nil
                completion(error)
            }
        }
    }
}

#if FLUXIT_PARITY
extension FirebaseBootstrap {
    static func runSessionCleanupIfRequested() -> Bool {
        let args = ProcessInfo.processInfo.arguments
        guard args.contains("-FluxItSessionCleanupCheck") else { return false }
        guard IosFirebaseEmulatorSettings.shared.enabled else { return false }
        func value(_ key: String) -> String {
            guard let index = args.firstIndex(of: key), index + 1 < args.count else { fatalError("Missing fixture argument") }
            return args[index + 1]
        }
        Task {
            do {
                let report = try await IosSessionCleanupCheck.shared.run(phase: value("-phase"), emailA: value("-emailA"), emailB: value("-emailB"),
                    password: value("-password"), uidA: value("-uidA"), uidB: value("-uidB"), bridge: FirebaseSessionCleanupProbe())
                print("FB-709 Apple \(report)")
                print("FB-709 END")
            } catch { print("FB-709 Apple FAILED \(error)\nFB-709 END") }
        }
        return true
    }
}

final class FirebaseSessionCleanupProbe: NSObject, IosSessionCleanupProbe {
    private var old: Firestore?
    private var settings: FirestoreSettings?
    func recordClient() { old = Firestore.firestore(); settings = old?.settings }
    func verifyRecreated() -> Bool {
        let fresh = Firestore.firestore()
        return fresh !== old && fresh.settings.isEqual(settings) && !fresh.settings.isSSLEnabled && fresh.settings.host.contains("127.0.0.1")
    }
    func disableNetwork(completion: @escaping (KotlinBoolean) -> Void) {
        Firestore.firestore().disableNetwork { error in completion(KotlinBoolean(value: error == nil)) }
    }
    func cachedName(path: String, completion: @escaping (String?, KotlinBoolean) -> Void) {
        Firestore.firestore().document(path).getDocument(source: .cache) { snapshot, error in
            if let error = error as NSError? {
                completion(nil, KotlinBoolean(value: error.code == FirestoreErrorCode.unavailable.rawValue))
            } else { completion(snapshot?.get(path.contains("/items/") ? "title" : "name") as? String, KotlinBoolean(value: true)) }
        }
    }
    func serverName(path: String, completion: @escaping (String?, KotlinBoolean) -> Void) {
        Firestore.firestore().document(path).getDocument(source: .server) { snapshot, error in
            completion(snapshot?.get(path.contains("/items/") ? "title" : "name") as? String, KotlinBoolean(value: error == nil))
        }
    }
    func verifyStorageCancellation(uid: String, completion: @escaping (KotlinBoolean) -> Void) {
        Task { @MainActor in
            do {
                let name = "fb709-storage-cancel"
                if FirebaseApp.app(name: name) == nil { FirebaseApp.configure(name: name, options: FirebaseApp.app()!.options) }
                let secondary = FirebaseApp.app(name: name)!
                let storage = Storage.storage(app: secondary)
                storage.useEmulator(withHost: "127.0.0.1", port: 9198)
                let bridge = FirebaseStorageBridge(storageProvider: { storage })
                let pending = Task { @MainActor in
                    try await withCheckedThrowingContinuation { (c: CheckedContinuation<Void, Error>) in
                        bridge.uploadData(photoRef: "users/\(uid)/items/fb709-item/cancelled-upload", data: Data([0xff, 0xd8, 0xff]), mimeType: "image/jpeg") {
                            if let error = $0 { c.resume(throwing: error) } else { c.resume() }
                        }
                    }
                }
                let pendingDownload = Task { @MainActor in
                    try await withCheckedThrowingContinuation { (c: CheckedContinuation<Void, Error>) in
                        bridge.downloadData(photoRef: "users/\(uid)/items/fb709-item/cancelled-upload", maxSize: 5_242_880) { _, error in
                            if let error = error { c.resume(throwing: error) } else { c.resume() }
                        }
                    }
                }
                await Task.yield()
                let cleaner = FirebaseSessionCleanupBridge(storageBridge: bridge)
                try await withCheckedThrowingContinuation { (c: CheckedContinuation<Void, Error>) in
                    cleaner.clear { if let error = $0 { c.resume(throwing: error) } else { c.resume() } }
                }
                do { try await pending.value; throw NSError(domain: "FB709", code: 1) }
                catch {
                    guard (error as NSError).code == StorageErrorCode.cancelled.rawValue else { throw error }
                }
                do { try await pendingDownload.value; throw NSError(domain: "FB709", code: 2) }
                catch {
                    guard (error as NSError).code == StorageErrorCode.cancelled.rawValue else { throw error }
                }
                secondary.delete { _ in }
                completion(KotlinBoolean(value: true))
            } catch { print("FB-709 Storage FAILED \(error)"); completion(KotlinBoolean(value: false)) }
        }
    }
}
#endif
