import ComposeApp
import FirebaseAuth
import FirebaseCore
import FirebaseFirestore
import FirebaseStorage
import UIKit

/// FB-007 initialization seam for the official Firebase Apple SDK.
///
/// This is deliberately the only place in the iOS app that touches Firebase SDK
/// types during Phase 0. It mirrors `AndroidFirebaseInitializer` in `androidMain`:
/// configure the default app, then - only when the build enabled it - point
/// Auth/Firestore/Storage at the local emulator suite.
///
/// The Apple SDK is integrated through Swift Package Manager into the Xcode
/// project rather than through Kotlin/Native cinterop, because `FirebaseStorage`
/// and the modern `FirebaseAuth` are Swift modules that cinterop cannot consume.
/// The emulator endpoints still come from the single shared source of truth: the
/// `FirebaseEmulatorConfig` constants generated by
/// `:composeApp:generateFirebaseEmulatorConfig`, surfaced to Swift through
/// `IosFirebaseEmulatorSettings` in `iosMain`.
///
/// `FB-103` added the second responsibility below: registering the Swift
/// implementation of the Kotlin `IosAuthBridge` protocol, which is how the
/// Firebase-neutral `AuthRepository` reaches Auth on iOS (PLAN-008). `FB-203` does the
/// same for `ListRepository`/Firestore lists, `FB-205` for `ItemRepository`/Firestore
/// items, and `FB-305` for `PhotoStorage`/Storage photos.
enum FirebaseBootstrap {

    private static var initialized = false

    /// Initializes the default `FirebaseApp` from the bundled
    /// `GoogleService-Info.plist` (gitignored, per `DEC-002b`).
    ///
    /// Must run before anything else touches the Firebase SDK, because
    /// `useEmulator` may only be called before a service instance is used.
    /// `AppDelegate.application(_:didFinishLaunchingWithOptions:)` is the earliest
    /// point the system gives us and runs strictly before any SwiftUI scene or
    /// view body - and therefore before `ContentView` creates the Compose view
    /// controller that starts Koin.
    static func start() {
        guard !initialized else { return }
        initialized = true

        guard FirebaseOptions.defaultOptions() != nil else {
            fatalError(
                "Firebase default app could not be initialized. "
                + "iosApp/GoogleService-Info.plist is missing from the app bundle; "
                + "fetch it from the Firebase Console (it is gitignored)."
            )
        }
        FirebaseApp.configure()

        if IosFirebaseEmulatorSettings.shared.enabled {
            connectToEmulators()
        }

        // FB-103: hand the Swift Auth implementation to the Kotlin framework. This runs
        // inside `didFinishLaunchingWithOptions`, strictly before `ContentView` creates
        // the Compose view controller that starts Koin, so the `single<AuthRepository>`
        // binding in `platformModule()` can never be resolved before the bridge exists.
        IosAuthBridgeRegistry.shared.register(bridge: FirebaseAuthBridge())

        // FB-203: same hand-off, for the Firestore list bridge.
        IosFirestoreListBridgeRegistry.shared.register(bridge: FirebaseListBridge())

        // FB-205: same hand-off, for the Firestore item bridge.
        IosFirestoreItemBridgeRegistry.shared.register(bridge: FirebaseItemBridge())

        // FB-305: same hand-off, for the Storage photo bridge.
        IosFirebaseStorageBridgeRegistry.shared.register(bridge: FirebaseStorageBridge())
    }

    #if FLUXIT_PARITY
    // FB-701: opt-in build symbol + emulator-only Kotlin gate + explicit launch argument.
    static func runParityIfRequested() {
        let arguments = ProcessInfo.processInfo.arguments
        guard arguments.contains("-FluxItParitySelfCheck"), IosFirebaseEmulatorSettings.shared.enabled else { return }
        func value(_ key: String) -> String? {
            guard let index = arguments.firstIndex(of: key), index + 1 < arguments.count else { return nil }
            return arguments[index + 1]
        }
        guard let email = value("-parityEmail"), let password = value("-parityPassword"),
              let marker = value("-parityMarker") else { print("FB-701 iOS FAILED missing-arguments\nFB-701 END"); return }
        Task {
            do {
                try await Firestore.firestore().disableNetwork()
                let offline = try await IosFirebaseRoomParityCheck.shared.runOffline(email: email, password: password, marker: marker) {
                    Task { try await Firestore.firestore().enableNetwork() }
                }
                print(offline)
                guard offline.contains("offline PASS") else { print("FB-701 iOS FAILED\nFB-701 END"); return }
                print(try await IosFirebaseRoomParityCheck.shared.run(email: email, password: password, marker: marker))
            } catch {
                try? await Firestore.firestore().enableNetwork()
                print("FB-701 iOS FAILED\nFB-701 END")
            }
        }
    }
    #endif

    /// FB-103 evidence hook: runs the emulator-backed Auth integration check and prints
    /// its report, then leaves the app running normally.
    ///
    /// Two independent gates keep this out of any ordinary build: the app must be
    /// launched with `-FluxItAuthSelfCheck`, and the Kotlin check itself refuses to run
    /// unless the build was configured with `fluxit.firebase.emulator.enabled=true`,
    /// which is the same flag that points Auth at the local emulator. It therefore
    /// cannot touch the live development project.
    static func runAuthSelfCheckIfRequested() {
        let arguments = ProcessInfo.processInfo.arguments
        let restorationPhase = arguments.contains("-FluxItAuthRestorePrepare") ? "prepare"
            : arguments.contains("-FluxItAuthRestoreVerify") ? "verify"
            : nil

        guard arguments.contains("-FluxItAuthSelfCheck") || restorationPhase != nil else { return }

        Task {
            do {
                let report: String
                if let phase = restorationPhase {
                    report = try await IosAuthIntegrationCheck.shared.runRestorationPhase(phase: phase)
                } else {
                    report = try await IosAuthIntegrationCheck.shared.run()
                }
                print(report)
            } catch {
                print("FB-103 iOS Auth integration check: THREW \(error)")
                print("FB-103 END")
            }
        }
    }

    /// FB-203 evidence hook: same shape as [runAuthSelfCheckIfRequested], for the
    /// Firestore list adapter. Guarded the same way: `-FluxItFirestoreListSelfCheck` on
    /// the launch arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runFirestoreListSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItFirestoreListSelfCheck") else { return }

        Task {
            do {
                let report = try await IosFirestoreListIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-203 iOS Firestore list integration check: THREW \(error)")
                print("FB-203 END")
            }
        }
    }

    /// FB-205 evidence hook: same shape as [runFirestoreListSelfCheckIfRequested], for
    /// the Firestore item adapter. Guarded the same way: `-FluxItFirestoreItemSelfCheck`
    /// on the launch arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runFirestoreItemSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItFirestoreItemSelfCheck") else { return }

        Task {
            do {
                let report = try await IosFirestoreItemIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-205 iOS Firestore item integration check: THREW \(error)")
                print("FB-205 END")
            }
        }
    }

    /// FB-206 evidence hook: same shape as [runFirestoreItemSelfCheckIfRequested], for
    /// the cross-client counter-consistency/conflict/malformed-document/reconnect
    /// checks. Guarded the same way: `-FluxItCrossClientSelfCheck` on the launch
    /// arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runCrossClientSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItCrossClientSelfCheck") else { return }

        Task {
            do {
                let report = try await IosFirestoreCrossClientIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-206 iOS cross-client integration check: THREW \(error)")
                print("FB-206 END")
            }
        }
    }

    /// FB-305 evidence hook: same shape as [runFirestoreItemSelfCheckIfRequested], for the
    /// Storage photo adapter. Guarded the same way: `-FluxItPhotoStorageSelfCheck` on the
    /// launch arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runPhotoStorageSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageSelfCheck") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.run()
                print(report)
            } catch {
                print("FB-305 iOS Storage integration check: THREW \(error)")
                print("FB-305 END")
            }
        }
    }

    /// `FB-307` evidence hook: interrupted-replace/orphan-detection/retry-recovery check.
    /// Guarded the same way: `-FluxItPhotoStorageInterruptedReplaceCheck` on the launch
    /// arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runPhotoStorageInterruptedReplaceCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageInterruptedReplaceCheck") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.runInterruptedReplaceCheck()
                print(report)
            } catch {
                print("FB-307 iOS Storage interrupted-replace check: THREW \(error)")
                print("FB-307 END")
            }
        }
    }

    /// `FB-307` evidence hook: the publish half of the cross-device/reinstall check pair.
    /// Guarded by `-FluxItPhotoStorageCrossDevicePublish` on the launch arguments, plus
    /// the Kotlin check's own emulator-enabled refusal. See
    /// `IosPhotoStorageIntegrationCheck`'s class KDoc for how to combine this with
    /// `runPhotoStorageCrossDeviceSubscribeIfRequested` for either a cross-device or a
    /// literal-reinstall run.
    static func runPhotoStorageCrossDevicePublishIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageCrossDevicePublish") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.runCrossDevicePublish()
                print(report)
            } catch {
                print("FB-307 iOS Storage cross-device publish check: THREW \(error)")
                print("FB-307 END")
            }
        }
    }

    /// `FB-307` evidence hook: the subscribe half of the cross-device/reinstall check
    /// pair. Guarded by `-FluxItPhotoStorageCrossDeviceSubscribe` on the launch
    /// arguments, plus the Kotlin check's own emulator-enabled refusal.
    static func runPhotoStorageCrossDeviceSubscribeIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItPhotoStorageCrossDeviceSubscribe") else { return }

        Task {
            do {
                let report = try await IosPhotoStorageIntegrationCheck.shared.runCrossDeviceSubscribe()
                print(report)
            } catch {
                print("FB-307 iOS Storage cross-device subscribe check: THREW \(error)")
                print("FB-307 END")
            }
        }
    }

    /// `FB-408` evidence hook: live pre-fix/post-fix reproduction of `FB-405`'s headline
    /// finding (a terminal Firestore listener error crashing the app process). Guarded the
    /// same way: `-FluxItDashboardListenerCrashSelfCheck` on the launch arguments, plus the
    /// Kotlin check's own emulator-enabled refusal. See
    /// `IosDashboardListenerCrashSelfCheck`'s KDoc for why this check's own try/catch here
    /// cannot mask the crash it exists to reproduce - that crash happens on a separate,
    /// unstructured `viewModelScope` coroutine, not on this `Task`'s own call stack.
    static func runDashboardListenerCrashSelfCheckIfRequested() {
        guard ProcessInfo.processInfo.arguments.contains("-FluxItDashboardListenerCrashSelfCheck") else { return }

        Task {
            do {
                let report = try await IosDashboardListenerCrashSelfCheck.shared.run()
                print(report)
            } catch {
                print("FB-408 iOS listener-crash self-check: THREW \(error)")
                print("FB-408 END")
            }
        }
    }

    private static func connectToEmulators() {
        // Passed through verbatim: the iOS simulator shares the host network stack,
        // so no Android-style 10.0.2.2 loopback translation applies here.
        let settings = IosFirebaseEmulatorSettings.shared
        let host = settings.host

        Auth.auth().useEmulator(withHost: host, port: Int(settings.authPort))

        // FB-203: `useEmulator(withHost:port:)` alone was empirically found NOT to
        // disable TLS reliably for this SDK version's gRPC transport when first
        // genuinely exercised (Firestore emulator work was unexercised on iOS through
        // FB-007/FB-008/FB-202) - the client kept attempting a TLS handshake against the
        // plaintext local emulator (`SSL_ERROR_SSL ... WRONG_VERSION_NUMBER`, confirmed
        // against a real emulator that answers plain HTTP on the same port). Setting
        // `isSSLEnabled = false` explicitly on the `FirestoreSettings` - the older,
        // lower-level documented pattern `useEmulator` is meant to be sugar for - is a
        // deliberate belt-and-suspenders fix, not a style preference. `useEmulator` is
        // still called first so a future SDK fix keeps working the documented way; must
        // still run before the first `Firestore` operation or the SDK throws.
        let firestore = Firestore.firestore()
        firestore.useEmulator(withHost: host, port: Int(settings.firestorePort))
        let firestoreSettings = firestore.settings
        firestoreSettings.isSSLEnabled = false
        firestore.settings = firestoreSettings

        Storage.storage().useEmulator(withHost: host, port: Int(settings.storagePort))
    }
}

/// Minimal application delegate whose only job is to give `FirebaseApp.configure()`
/// a deterministic home. `iOSApp.swift` is a bare SwiftUI `@main` with no delegate,
/// so this is attached via `@UIApplicationDelegateAdaptor`. Firebase documents this
/// as the SwiftUI integration point, and later Firebase features that need UIKit
/// app-lifecycle callbacks (push notifications, phone auth) already have a home here.
final class AppDelegate: NSObject, UIApplicationDelegate {
    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
    ) -> Bool {
        FirebaseBootstrap.start()
        #if FLUXIT_PARITY
        FirebaseBootstrap.runParityIfRequested()
        #endif
        FirebaseBootstrap.runAuthSelfCheckIfRequested()
        FirebaseBootstrap.runFirestoreListSelfCheckIfRequested()
        FirebaseBootstrap.runFirestoreItemSelfCheckIfRequested()
        FirebaseBootstrap.runCrossClientSelfCheckIfRequested()
        FirebaseBootstrap.runPhotoStorageSelfCheckIfRequested()
        FirebaseBootstrap.runPhotoStorageInterruptedReplaceCheckIfRequested()
        FirebaseBootstrap.runPhotoStorageCrossDevicePublishIfRequested()
        FirebaseBootstrap.runPhotoStorageCrossDeviceSubscribeIfRequested()
        FirebaseBootstrap.runDashboardListenerCrashSelfCheckIfRequested()
        return true
    }
}
